<section id="contacto">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 nopadding">
				<h2 class="col-xs-12 noHorizontalPadding vxpadding nopaddingTop nomargin">Comienza hoy</h2>
				<div class="col-xs-12 col-sm-6">
					<div class="col-xs-12 noHorizontalPadding iconFooter">
						<img src="assets/img/logo_svg.svg" alt="">
						<div class="col-xs-12 text-left">
							<h3 class="col-xs-12 nopadding nomargin bold">SIGA</h3>
							<h5 class="col-xs-12 nopadding nomargin">Sistema Informático de Gestión Avanzada</h5>
						</div>
					</div>
					<div class="col-xs-12 noHorizontalPadding vxpadding social">
						<div class="col-xs-3 item facebook text-center">
							<a href="https://www.facebook.com/sigasystem" target="_blank" class="col-xs-12 nopadding centered">
								<img src="assets/img/icons/facebook_2.svg" alt="">
							</a>
						</div>
						<div class="col-xs-3 item instagram text-center">
							<a href="https://www.instagram.com/Sigasystem/" target="_blank" class="col-xs-12 nopadding centered">
								<img src="assets/img/icons/inst_2.svg" alt="">
							</a>
						</div>
						<div class="col-xs-3 item youtube text-center">
							<a href="https://www.youtube.com/channel/UCG9h7azZ9Wu2MpcEvNEJ2dQ/videos?view_as=subscriber" target="_blank" class="col-xs-12 nopadding centered">
								<img src="assets/img/icons/youtube_2.svg" alt="">
							</a>
						</div>
						<div class="col-xs-3 item playstore text-center">
							<a href="https://play.google.com/store/apps/details?id=com.siga2018" href="_blank" class="col-xs-12 nopadding centered">
								<img src="assets/img/icons/playstore_2.svg" alt="">
							</a>
						</div>
					</div>
					<div class="col-xs-12 noHorizontalPadding">
						<p class="col-xs-12 nopadding text-left">SIGA es un sistema informático que trabaja continuamente ofreciendo soluciones de vanguardia.</p>
					</div>
					<div class="col-xs-12 noHorizontalPadding">
						<p class="col-xs-12 nopadding text-center textBlue bold">Si deseas hacer tu negocio rentable llámanos hoy <br>Teléfono <a href="tel:+5113939907">(+51) 1393 99 07</a></p>
					</div>
					<div class="col-xs-12 noHorizontalPadding vpadding text-center">
						<a href="prueba" class="btn3 centered">QUIERO MI PRUEBA GRATIS</a>
					</div>
				</div>
				<div class="col-xs-12 col-sm-6">
					<form class="col-xs-12 noHorizontalPadding text-left" id="Contacto">
							<input type="hidden" name="captcha" id="captcha" value="">
  						<div class="col-xs-12 col-sm-6 form-group">
  						  	<label class="bold" for="nombre">Nombre</label>
  						  	<input type="text" class="form-control" id="nombre" name="nombre">
  						</div>
  						<div class="col-xs-12 col-sm-6 form-group">
  						  	<label class="bold" for="telefono">Telefono</label>
  						  	<input type="text" class="form-control" id="telefono" name="telefono">
  						</div>
  						<div class="col-xs-12 form-group">
  						  	<label class="bold" for="email">Email</label>
  						  	<input type="text" class="form-control" id="email" name="email">
  						</div>
  						<div class="col-xs-12 form-group">
  						  	<label class="bold" for="mensaje">Mensaje</label>
  						  	<textarea name="mensaje" class="form-control" id="mensaje" name="mensaje" cols="30" rows="5"></textarea>
  						</div>
  						<div class="col-xs-12 form-group text-center">
							<a href="#" class="btn2 centered" id="btnEnviar">ENVIAR</a>
  						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</section>
