<span id="contacto"></span>
<section id="contacto2">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 nopadding">
        <div class="col-xs-12 col-sm-5 col-md-4 col-lg-3 text-left">
    				<h2 class="col-xs-12 noHorizontalPadding nomargin">Contáctanos</h2>
            <div class="col-xs-12 noHorizontalPadding vpadding social_dats">
              <div class="col-xs-12 noHorizontalPadding item">
                <a href="mailto: ventas@siga.com.pe">
                  <img src="assets/img/icons/contacto2/email_orange.svg" alt="">
                  ventas@siga.com.pe
                </a>
              </div>
              <div class="col-xs-12 noHorizontalPadding item">
                <a href="https://api.whatsapp.com/send?phone=513939907" target="_blank">
                  <img src="assets/img/icons/contacto2/wp_orange.svg" alt="">
                  +51 1393 9907
                </a>
              </div>
              <div class="col-xs-12 noHorizontalPadding item">
                <a href="tel:+51013939907">
                  <img src="assets/img/icons/contacto2/llamada_orange.svg" alt="">
                  01 393 99 07
                </a>
              </div>
            </div>
        </div>
				<div class="col-xs-12 col-sm-7 col-md-8 col-lg-9">
					<form class="col-xs-12 noHorizontalPadding text-left" id="Contacto">
							<input type="hidden" name="captcha" id="captcha" value="">
  						<div class="col-xs-12 form-group">
  						  	<input type="text" class="form-control" id="nombre" name="nombre" placeholder="Nombre y Apellido">
  						</div>
  						<div class="col-xs-12 form-group">
  						  	<input type="text" class="form-control" id="email" name="email" placeholder="Correo">
  						</div>
              <div class="col-xs-12 form-group">
  						  	<input type="text" class="form-control" id="telefono" name="telefono" placeholder="Teléfono">
  						</div>
  						<div class="col-xs-12 form-group">
  						  	<textarea name="mensaje" class="form-control" id="mensaje" name="mensaje" cols="30" rows="5" placeholder="Mensaje"></textarea>
  						</div>
  						<div class="col-xs-12 form-group text-center">
							  <a href="#" class="btn2 centered" id="btnEnviar">ENVIAR</a>
  						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</section>
