<section id="callToAction">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<h2 class="col-xs-12 noHorizontalPadding textWhite">¿Necesitas los equipos? Podemos ayudarte</h2>
				<div class="col-xs-12 text-center">
					<a href="prueba" class="btn5 centered">COTIZAR</a>
				</div>
			</div>
		</div>
	</div>
</section>

<section id="footer">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<p class="col-xs-12 noHorizontalPadding text-center">Correo: ventas@siga.com.pe</p>
				<p class="col-xs-12 noHorizontalPadding text-center">Telefono: +51 1393 9907</p>
				<p class="col-xs-12 noHorizontalPadding text-center" style="color: #FFFFFF !important;">Dirección: Jr. Puno 1089 - Cercado de Lima, Lima. Perú.</p>
				<div class="col-xs-12 noHorizontalPadding vpadding icons text-center">
					<div class="col-xs-12 col-sm-10 col-md-8 nopadding centered">
						<div class="col-xs-4 noHorizontalPadding text-center">
							<img src="assets/img/icons/pay_1.svg" alt="" class="col-xs-12 noHorizontalPadding centered">
						</div>
						<div class="col-xs-4 noHorizontalPadding text-center">
							<img src="assets/img/icons/pay_2.svg" alt="" class="col-xs-12 noHorizontalPadding centered">
						</div>
						<div class="col-xs-4 noHorizontalPadding text-center">
							<img src="assets/img/icons/pay_3.svg" alt="" class="col-xs-12 noHorizontalPadding centered">
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<div id="SkypeButton_Call_yinblack_1">
 <script type="text/javascript">
 Skype.ui({
 "name": "call",
 "element": "SkypeButton_Call_yinblack_1",
 "participants": ["yinblack"]
 });
 </script>
</div>


</body>

<!-- Latest compiled and minified JavaScript -->

<script src='assets/js/jquery.min.js'></script>
<script src="assets/js/bootstrap.min.js"></script>
<?php if(isset($this->js)) echo $this->js; ?>
<script src='assets/js/dev.js'></script>
<script src='assets/js/Menu.js'></script>
</html>
