<section id="footer2">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 text-left">
          <div class="col-xs-12 col-md-7 noHorizontalPadding">
            <div class="col-xs-12 col-sm-4 block_footer">
              <h4 class="col-xs-12 noHorizontalPadding nomarginTop bold textWhite">Empresa</h4>
              <a href="quienes-somos" class="col-xs-12 noHorizontalPadding nomargin textWhite">Nosotros</a>
              <a href="#" class="col-xs-12 noHorizontalPadding nomargin textWhite">Fortalezas</a>
              <a href="#" class="col-xs-12 noHorizontalPadding nomargin textWhite">FAQ</a>
            </div>
            <div class="col-xs-12 col-sm-4 block_footer">
              <h4 class="col-xs-12 noHorizontalPadding nomarginTop bold textWhite">Más</h4>
              <a href="#" class="col-xs-12 noHorizontalPadding nomargin textWhite">Manuales</a>
              <a href="video-tutoriales" class="col-xs-12 noHorizontalPadding nomargin textWhite">Video tutoriales</a>
              <a href="Quiero-ser-partner" class="col-xs-12 noHorizontalPadding nomargin textWhite">Sé un socio SIGA</a>
            </div>
            <div class="col-xs-12 col-sm-4 block_footer">
              <h4 class="col-xs-12 noHorizontalPadding nomarginTop bold textWhite">Contacto</h4>
              <a href="mailto:ventas@siga.com.pe" class="col-xs-12 noHorizontalPadding nomargin textWhite">ventas@siga.com.pe</a>
              <a href="tel:+5113939907" class="col-xs-12 noHorizontalPadding nomargin textWhite">Télefono +51 1393 9907</a>
              <a class="col-xs-12 noHorizontalPadding nomargin textWhite" style="color: #FFFFFF !important;">Cercado de Lima, Lima. Perú</a>
            </div>
          </div>
          <div class="col-xs-12 col-md-5 noHorizontalPadding text-center">
            <div class="col-xs-12 col-md-10 centered icons_footer">
              <div class="col-xs-3 noHorizontalPadding text-center item">
                  <a href="https://www.facebook.com/SigaSystem/" target="_blank" class="centered">
                    <img src="assets/img/icons/contacto2/facebook_2.svg" alt="">
                  </a>
              </div>
              <div class="col-xs-3 noHorizontalPadding text-center item">
                  <a href="https://www.youtube.com/channel/UCG9h7azZ9Wu2MpcEvNEJ2dQ" target="_blank" class="centered">
                    <img src="assets/img/icons/contacto2/youtube_2.svg" alt="">
                  </a>
              </div>
              <div class="col-xs-3 noHorizontalPadding text-center item">
                  <a href="https://twitter.com/SystemSiga" target="_blankhttps://twitter.com/SystemSiga" class="centered">
                    <img src="assets/img/icons/contacto2/twitter_2.svg" alt="">
                  </a>
              </div>
              <div class="col-xs-3 noHorizontalPadding text-center item">
                  <a href="https://www.instagram.com/Sigasystem/" target="_blank" class="centered">
                    <img src="assets/img/icons/contacto2/inst_2.svg" alt="">
                  </a>
              </div>
            </div>
          </div>
			</div>
		</div>
	</div>
</section>

<section id="boton_bar">
	<div class="container-fluid">
		<div class="row">
			<div class="col-xs-12">
        <h4 class="col-xs-12 noHorizontalPadding text-center">Todos los documentos emitidos desde SIGA pueden ser consultados a través del portal web a la SUNAT</h4>
			</div>
      <div class="col-xs-12 noHorizontalPadding">
          <h3 class="col-xs-12 noHorizontalPadding text-left">SIGA está respaldado por</h3>
          <div class="col-xs-12 noHorizontalPadding img_respaldos">
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3 noHorizontalPadding text-center">
              <img src="assets/img/icons/bot_bar/icon1.png" alt="">
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3 noHorizontalPadding text-center">
              <img src="assets/img/icons/bot_bar/icon2.png" alt="">
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3 noHorizontalPadding text-center">
              <img src="assets/img/icons/bot_bar/icon3.png" alt="">
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3 noHorizontalPadding text-center">
              <img src="assets/img/icons/bot_bar/icon4.png" alt="">
            </div>
          </div>
      </div>
		</div>
	</div>
</section>

</div>


</body>

<!-- Latest compiled and minified JavaScript -->

<script src='assets/js/jquery.min.js'></script>
<script src="assets/js/bootstrap.min.js"></script>
<?php if(isset($this->js)) echo $this->js; ?>
<script src='assets/js/dev.js'></script>
<script src='assets/js/Menu.js'></script>
</html>
