<section id="slide" class="startSection">
	<div class="col-xs-12 nopadding item item1">
		<div class="container">
			<div class="row">
				<div class="col-xs-12 col-sm-6 height">
					<div class="vertical">
						<div class="col-xs-12 nopadding">
							<h1 class="col-xs-12 nopadding regular text-left" style="line-height: 1.2;">Ahora es más fácil y económico tener un software de punto de venta</h1>
							<div class="col-xs-12 noHorizontalPadding vpadding text-left">
								<a href="#" class="btn1">DEMO GRATIS</a>
								<a href="#" class="btn2">CONTACTENOS</a>
							</div>
						</div>
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 height">
					<img src="assets/img/icons/slide1.svg" alt="">
				</div>
			</div>
		</div>
	</div>
</section>

<section id="beneficios" class="backBlue nopaddingBottom">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 nopadding">
				<h2 class="col-xs-12 noHorizontalPadding vxpadding nopaddingTop nomargin">¿ Como me beneficia iCloudPOS ?</h2>
				<div class="col-xs-12 noHorizontalPadding vpadding text-center">
					<p class="col-xs-12 col-sm-10 col-md-8 nopadding centered">No necesitas de instalaciones ni adquirir equipos de alto costo, ademas contaras con soporte y asistencia permanente</p>
					<p class="col-xs-12 col-sm-10 col-md-8 nopadding centered">iCloudPOS, es un sistema de control y gestíon interno</p>
				</div>
				<div class="col-xs-12 nopadding containerItemSlide">
					<div class="col-xs-12 col-sm-5 col-md-4 content_arrows">
						<div class="col-xs-12 noHorizontalPadding text-center">
							<h3 class="col-xs-8 centered regular" style="line-height: 1.2;">4 Simples tips para empezar a vender e impulsar tu negocio</h3>
						</div>
						<div class="col-xs-12 arrows">
							<a href="#" class="pull-left">
								<img src="assets/img/icons/arrow_slide_tips.svg">
							</a>
							<a href="#" class="pull-right">
								<img src="assets/img/icons/arrow_slide_tips.svg">
							</a>
						</div>
					</div>
					<div class="col-xs-12 col-sm-7 col-md-8 nopadding" id="slideTips">
						<div class="col-xs-12 col-sm-6 nopadding itemSlide text-center" style="background-image: url('assets/img/image_slide_tip_1.jpg');">
							<div class="col-xs-12 nopadding centered text-left">
								<div class="vertical end">
									<span class="backGreen">Finanzas</span>
									<h4 class="col-xs-12 noHorizontalPadding vpadding nomargin">
										Manejo completo de finanzas
									</h4>
									<p class="col-xs-12 noHorizontalPadding vpadding nomargin nopaddingTop">Conoce el diario de ventas, pago a proveedores, gastos del día a día, tus pagos de prestamos y más</p>
								</div>
							</div>
						</div>
						<div class="col-xs-12 col-sm-6 nopadding itemSlide text-center" style="background-image: url('assets/img/image_slide_tip_1.jpg');">
							<div class="col-xs-12 nopadding centered text-left">
								<div class="vertical end">
									<span class="backPink">INVENTARIO</span>
									<h4 class="col-xs-12 noHorizontalPadding vpadding nomargin">
										Inventario centralizado
									</h4>
									<p class="col-xs-12 noHorizontalPadding vpadding nomargin nopaddingTop">Consulta tu inventario agrupado por todos tus almacenes, detallado por almacen o realiza comparativos de inventario entre almacenes</p>
								</div>
							</div>
						</div>
						<div class="col-xs-12 col-sm-6 nopadding itemSlide text-center" style="background-image: url('assets/img/image_slide_tip_1.jpg');">
							<div class="col-xs-12 nopadding centered text-left">
								<div class="vertical end">
									<span class="backGreen">Finanzas</span>
									<h4 class="col-xs-12 noHorizontalPadding vpadding nomargin">
										Manejo completo de finanzas
									</h4>
									<p class="col-xs-12 noHorizontalPadding vpadding nomargin nopaddingTop">Conoce el diario de ventas, pago a proveedores, gastos del día a día, tus pagos de prestamos y más</p>
								</div>
							</div>
						</div>
						<div class="col-xs-12 col-sm-6 nopadding itemSlide text-center" style="background-image: url('assets/img/image_slide_tip_1.jpg');">
							<div class="col-xs-12 nopadding centered text-left">
								<div class="vertical end">
									<span class="backPink">INVENTARIO</span>
									<h4 class="col-xs-12 noHorizontalPadding vpadding nomargin">
										Inventario centralizado
									</h4>
									<p class="col-xs-12 noHorizontalPadding vpadding nomargin nopaddingTop">Consulta tu inventario agrupado por todos tus almacenes, detallado por almacen o realiza comparativos de inventario entre almacenes</p>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-xs-12 more">
					<a href="#" class="col-xs-12">VER MÁS</a>
				</div>
			</div>
		</div>
	</div>
</section>

<section id="postventa" style="background-image: url('assets/img/back_postventa_landing2.jpg');">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 nopadding">
				<div class="col-xs-12 col-sm-6 nopadding text-center">
					<div class="col-xs-12 centered box">
						<div class="col-xs-12 noHorizontalPadding">
							<img src="assets/img/icons/postventa1.svg" alt="">
							<div class="col-xs-12 nopadding lined"></div>
							<div class="col-xs-12 noHorizontalPadding vpadding nopaddingTop text">
								<span class="pull-left">Usuarios</span>
								<span class="pull-right">120</span>
							</div>
							<div class="col-xs-12 nopadding metric">
								<div class="col-xs-4 nopadding"></div>
							</div>
						</div>
						<div class="col-xs-12 noHorizontalPadding">
							<img src="assets/img/icons/postventa2.svg" alt="">
							<div class="col-xs-12 nopadding lined"></div>
							<div class="col-xs-12 noHorizontalPadding vpadding nopaddingTop text">
								<span class="pull-left">Sucursales con iCloudPOS</span>
								<span class="pull-right">250</span>
							</div>
							<div class="col-xs-12 nopadding metric">
								<div class="col-xs-8 nopadding"></div>
							</div>
						</div>
						<div class="col-xs-12 noHorizontalPadding">
							<img src="assets/img/icons/postventa3.svg" alt="">
							<div class="col-xs-12 nopadding lined"></div>
							<div class="col-xs-12 noHorizontalPadding vpadding nopaddingTop text">
								<span class="pull-left">Ventas realizadas con iCloudP</span>
								<span class="pull-right">1300</span>
							</div>
							<div class="col-xs-12 nopadding metric">
								<div class="col-xs-10 nopadding"></div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 nopadding text-center contentPlay">
					<div class="vertical">
						<div class="col-xs-12 nopadding">
							<h3 class="col-xs-12 col-sm-10 col-md-8 nopadding centered">Nuestro mejor servicio <strong>es la post-venta</strong></h3>
							<div class="col-xs-12 nopadding text-center">
								<img src="assets/img/play_red.svg" alt="" class="col-xs-12 centered">
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<section id="testimonios" class="backBlue">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 nopadding">
				<div class="col-xs-12 col-sm-8 col-md-7 containerSlideTestimonios">
					<div class="col-xs-12 nopadding" id="slideTestimonios">
						<div class="col-xs-12 text-center nopadding item">
							<div class="col-xs-12 text-left nopadding centered">
								<img src="assets/img/testimonios/1.jpg" alt="">
								<div class="col-xs-12">
									<img src="assets/img/testimonios/1.jpg" alt="">
									<div class="col-xs-12 nopadding heitheen">
										<div class="vertical">
											<div class="col-xs-12">
												<span class="col-xs-12 textWhite">Sistema practico y adaptable, pero más aun,excelente servicio de la empresa que lo desarrolla.</span>
											</div>
										</div>
									</div>
									<div class="col-xs-12">
										<span class="textWhite pull-left">IAN MORAN</span>
										<a class="textWhite pull-right" href="#">INNOVALED</a>
									</div>
								</div>
							</div>
						</div>
						<div class="col-xs-12 text-center nopadding item">
							<div class="col-xs-12 text-left nopadding centered">
								<img src="assets/img/testimonios/2.jpg" alt="">
								<div class="col-xs-12">
									<img src="assets/img/testimonios/2.jpg" alt="">
									<div class="col-xs-12 nopadding heitheen">
										<div class="vertical">
											<div class="col-xs-12">
												<span class="col-xs-12 textWhite">Sistema practico y adaptable, pero más aun,excelente servicio de la empresa que lo desarrolla.</span>
											</div>
										</div>
									</div>
									<div class="col-xs-12">
										<span class="textWhite pull-left">IAN MORAN</span>
										<a class="textWhite pull-right" href="#">INNOVALED</a>
									</div>
								</div>
							</div>
						</div>
						<div class="col-xs-12 text-center nopadding item">
							<div class="col-xs-12 text-left nopadding centered">
								<img src="assets/img/testimonios/3.jpg" alt="">
								<div class="col-xs-12">
									<img src="assets/img/testimonios/3.jpg" alt="">
									<div class="col-xs-12 nopadding heitheen">
										<div class="vertical">
											<div class="col-xs-12">
												<span class="col-xs-12 textWhite">Sistema practico y adaptable, pero más aun,excelente servicio de la empresa que lo desarrolla.</span>
											</div>
										</div>
									</div>
									<div class="col-xs-12">
										<span class="textWhite pull-left">IAN MORAN</span>
										<a class="textWhite pull-right" href="#">INNOVALED</a>
									</div>
								</div>
							</div>
						</div>
						<div class="col-xs-12 text-center nopadding item">
							<div class="col-xs-12 text-left nopadding centered">
								<img src="assets/img/testimonios/4.jpg" alt="">
								<div class="col-xs-12">
									<img src="assets/img/testimonios/4.jpg" alt="">
									<div class="col-xs-12 nopadding heitheen">
										<div class="vertical">
											<div class="col-xs-12">
												<span class="col-xs-12 textWhite">Sistema practico y adaptable, pero más aun,excelente servicio de la empresa que lo desarrolla.</span>
											</div>
										</div>
									</div>
									<div class="col-xs-12">
										<span class="textWhite pull-left">IAN MORAN</span>
										<a class="textWhite pull-right" href="#">INNOVALED</a>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="controls text-center">
						<div class="line"></div>
						<div class="vertical">
							<div class="col-xs-12 nopadding">
								<a href="#" class="item active">
									<svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 319.4 319.4" style="enable-background:new 0 0 319.4 319.4;" xml:space="preserve">
										<rect x="3" y="3" transform="matrix(-1.836970e-16 1 -1 -1.836970e-16 319.4134 2.842171e-14)" class="st0" width="313.4" height="313.4"/>
										<rect x="79.4" y="79.4" transform="matrix(-1.836970e-16 1 -1 -1.836970e-16 319.4134 2.842171e-14)" class="st1" width="160.5" height="160.5"/>
									</svg>
								</a>
								<a href="#" class="item">
									<svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 319.4 319.4" style="enable-background:new 0 0 319.4 319.4;" xml:space="preserve">
										<rect x="3" y="3" transform="matrix(-1.836970e-16 1 -1 -1.836970e-16 319.4134 2.842171e-14)" class="st0" width="313.4" height="313.4"/>
										<rect x="79.4" y="79.4" transform="matrix(-1.836970e-16 1 -1 -1.836970e-16 319.4134 2.842171e-14)" class="st1" width="160.5" height="160.5"/>
									</svg>
								</a>
								<a href="#" class="item">
									<svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 319.4 319.4" style="enable-background:new 0 0 319.4 319.4;" xml:space="preserve">
										<rect x="3" y="3" transform="matrix(-1.836970e-16 1 -1 -1.836970e-16 319.4134 2.842171e-14)" class="st0" width="313.4" height="313.4"/>
										<rect x="79.4" y="79.4" transform="matrix(-1.836970e-16 1 -1 -1.836970e-16 319.4134 2.842171e-14)" class="st1" width="160.5" height="160.5"/>
									</svg>
								</a>
								<a href="#" class="item">
									<svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 319.4 319.4" style="enable-background:new 0 0 319.4 319.4;" xml:space="preserve">
										<rect x="3" y="3" transform="matrix(-1.836970e-16 1 -1 -1.836970e-16 319.4134 2.842171e-14)" class="st0" width="313.4" height="313.4"/>
										<rect x="79.4" y="79.4" transform="matrix(-1.836970e-16 1 -1 -1.836970e-16 319.4134 2.842171e-14)" class="st1" width="160.5" height="160.5"/>
									</svg>
								</a>
							</div>
						</div>
					</div>
				</div>
				<div class="col-xs-12 col-sm-4 col-md-5 containerSlideClientes">
					<h3 class="col-xs-12 vpadding nomargin regular">Nuestro clientes</h3>
					<div class="col-xs-12 noHorizontalPadding text-center" id="slideIconClientes">
						<div class="col-xs-12 text-center itemSlideIconCliente">
							<div class="col-xs-12 centered">
								<div class="vertical">
									<div class="col-xs-12 nopadding">
										<div class="col-xs-12 nopadding text-center">
											<img src="assets/img/icons/nuestros_clientes/1.svg" alt="" class="centered">
										</div>
										<div class="col-xs-12 nopadding text-center">
											<h4 class="col-xs-12 centered">Abarrotes al por menor y mayor</h4>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="col-xs-12 text-center itemSlideIconCliente">
							<div class="col-xs-12 centered">
								<div class="vertical">
									<div class="col-xs-12 nopadding">
										<div class="col-xs-12 nopadding text-center">
											<img src="assets/img/icons/nuestros_clientes/2.svg" alt="" class="centered">
										</div>
										<div class="col-xs-12 nopadding text-center">
											<h4 class="col-xs-12 centered">Minimarket</h4>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="col-xs-12 text-center itemSlideIconCliente">
							<div class="col-xs-12 centered">
								<div class="vertical">
									<div class="col-xs-12 nopadding">
										<div class="col-xs-12 nopadding text-center">
											<img src="assets/img/icons/nuestros_clientes/3.svg" alt="" class="centered">
										</div>
										<div class="col-xs-12 nopadding text-center">
											<h4 class="col-xs-12 centered">Importador</h4>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<section id="precios" class="backBlue nopaddingTop">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 nopadding">
				<h2 class="col-xs-12 noHorizontalPadding vxpadding nopaddingTop nomargin">Precios iCloudPOS</h2>
				<div class="col-xs-12 noHorizontalPadding text-center">
					<p class="col-xs-12 nopadding text-center nomargin">Nuestro servicio incluye soporte y capacitación permanente, no tenemos precios ocultos</p>
					<p class="col-xs-12 col-sm-8 vpadding noHorizontalPadding centered">Elige el plan que mejor se acomode a tu negocio. Puedes simular y personalizar según el número de sucursales que necesites</p>
				</div>
			</div>
			<div class="col-xs-12 nopadding">
				<div class="col-xs-6 col-sm-3 text-center control_precios">
					<a href="#" class="col-xs-12 centered active">
						<div class="vertical">
							<div class="col-xs-12 nopadding text-center">
								<img src="assets/img/icons/precios_2/1.svg" alt="" class="col-xs-12 centered">
							</div>
							<h4 class="col-xs-12 text-center textRed">FREE</h4>
						</div>
					</a>
				</div>
				<div class="col-xs-6 col-sm-3 text-center control_precios">
					<a href="#" class="col-xs-12 centered">
						<div class="vertical">
							<div class="col-xs-12 nopadding text-center">
								<img src="assets/img/icons/precios_2/2.svg" alt="" class="col-xs-12 centered">
							</div>
							<h4 class="col-xs-12 text-center textRed">BASICO</h4>
						</div>
					</a>
				</div>
				<div class="col-xs-6 col-sm-3 text-center control_precios">
					<a href="#" class="col-xs-12 centered">
						<div class="vertical">
							<div class="col-xs-12 nopadding text-center">
								<img src="assets/img/icons/precios_2/3.svg" alt="" class="col-xs-12 centered">
							</div>
							<h4 class="col-xs-12 text-center textRed">ESTANDAR</h4>
						</div>
					</a>
				</div>
				<div class="col-xs-6 col-sm-3 text-center control_precios">
					<a href="#" class="col-xs-12 centered">
						<div class="vertical">
							<div class="col-xs-12 nopadding text-center">
								<img src="assets/img/icons/precios_2/4.svg" alt="" class="col-xs-12 centered">
							</div>
							<h4 class="col-xs-12 text-center textRed">FULL</h4>
						</div>
					</a>
				</div>
			</div>
			<div class="col-xs-12 noHorizontalPadding" id="slide_precios">

				<div class="col-xs-12 nopadding text-center item_slide_precio">
					<div class="col-xs-12 nopadding centered">
						<div class="col-xs-12 col-sm-4 start_info">
							<div>
								<div class="col-xs-12 nopadding text-center">
									<img src="assets/img/icons/precios_2/1.svg" alt="" class="col-xs-12 centered">
								</div>
								<h4 class="col-xs-12 noHorizontalPadding regular textRed">FREE</h4>
								<h3 class="col-xs-12 noHorizontalPadding bold"><small>$</small> 350.00 / <small>Anual</small></h3>
								<ul class="col-xs-12 noHorizontalPadding">
									<li>Punto de venta</li>
									<li>Compras y gastos</li>
									<li>Control de inventario</li>
									<li>Caja y bancos</li>
									<li>Proveedores ( cuentas por pagar )</li>
									<li>Clientes ( cuentas por cobrar )</li>
									<li>Informes en linea</li>
									<li>App de ventas</li>
									<li>Certificado SSL</li>
								</ul>
							</div>
						</div>
						<div class="col-xs-12 col-sm-8 info">
							<div class="vertical">
								<div class="col-xs-12 vpadding rw">
									<span class="col-xs-12 regular noHorizontalPadding text-left"># Sucursales</span>
									<div class="col-xs-12 noHorizontalPadding">
										<input id="range" class="range" type="range" min="0" max="3" step="1" value="2" data-orientation="horizontal">
										<div class="col-xs-12 noHorizontalPadding vpadding numbs">
											<span class="0">0</span>
											<span class="1">1</span>
											<span class="2 active">2</span>
											<span class="3">Ilimitado</span>
										</div>
									</div>
								</div>
								<div class="col-xs-12 vpadding rw">
									<span class="col-xs-12 regular noHorizontalPadding text-left"># Usuarios</span>
									<div class="col-xs-12 noHorizontalPadding">
										<input id="range" class="range" type="range" min="0" max="4" step="1" value="2" data-orientation="horizontal">
										<div class="col-xs-12 noHorizontalPadding vpadding numbs">
											<span class="0">0</span>
											<span class="1">3</span>
											<span class="2 active">10</span>
											<span class="3">15</span>
											<span class="4">Ilimitado</span>
										</div>
									</div>
								</div>
								<div class="col-xs-12 vpadding rw">
									<span class="col-xs-12 regular noHorizontalPadding text-left"># Usuarios</span>
									<div class="col-xs-12 noHorizontalPadding">
										<input id="range" class="range" type="range" min="0" max="6" step="1" value="2" data-orientation="horizontal">
										<div class="col-xs-12 noHorizontalPadding vpadding numbs">
											<span class="0">0</span>
											<span class="1">100</span>
											<span class="2">500</span>
											<span class="3 active">1000</span>
											<span class="4">1500</span>
											<span class="5">3000</span>
											<span class="6">Ilimitado</span>
										</div>
									</div>
								</div>
								<div class="col-xs-12 noHorizontalPadding vxpadding">
									<div class="col-xs-12 col-sm-6 radios">
										<span class="col-xs-12 regular noHorizontalPadding text-left">Dominio propio</span>
										<div class="col-xs-6">
											<label class="col-xs-12 noHorizontalPadding" for="dominio">Si</label>
											<input type="radio" name="dominio">
										</div>
										<div class="col-xs-6">
											<label class="col-xs-12 noHorizontalPadding" for="dominio">No</label>
											<input type="radio" name="dominio">
										</div>
									</div>
									<div class="col-xs-12 col-sm-6 radios">
										<span class="col-xs-12 regular noHorizontalPadding text-left">Facturación electronica</span>
										<div class="col-xs-6">
											<label class="col-xs-12 noHorizontalPadding" for="facturacion">Si</label>
											<input type="radio" name="facturacion">
										</div>
										<div class="col-xs-6">
											<label class="col-xs-12 noHorizontalPadding" for="facturacion">No</label>
											<input type="radio" name="facturacion">
										</div>
									</div>
								</div>
								<div class="col-xs-12 noHorizontalPadding vxpadding">
									<a href="#" class="btn2 pull-right">PRUEBA GRATIS</a>
									<a href="#" class="btn1 pull-right">CONTRATAR</a>
								</div>
							</div>
						</div>
					</div>
				</div>
				
				<div class="col-xs-12 nopadding text-center item_slide_precio">
					<div class="col-xs-12 nopadding centered">
						<div class="col-xs-12 col-sm-4 start_info">
							<div>
								<div class="col-xs-12 nopadding text-center">
									<img src="assets/img/icons/precios_2/2.svg" alt="" class="col-xs-12 centered">
								</div>
								<h4 class="col-xs-12 noHorizontalPadding regular textRed">BASICO</h4>
								<h3 class="col-xs-12 noHorizontalPadding bold"><small>$</small> 350.00 / <small>Anual</small></h3>
								<ul class="col-xs-12 noHorizontalPadding">
									<li>Punto de venta</li>
									<li>Compras y gastos</li>
									<li>Control de inventario</li>
									<li>Caja y bancos</li>
									<li>Proveedores ( cuentas por pagar )</li>
									<li>Clientes ( cuentas por cobrar )</li>
									<li>Informes en linea</li>
									<li>App de ventas</li>
									<li>Certificado SSL</li>
								</ul>
							</div>
						</div>
						<div class="col-xs-12 col-sm-8 info">
							<div class="vertical">
								<div class="col-xs-12 vpadding rw">
									<span class="col-xs-12 regular noHorizontalPadding text-left"># Sucursales</span>
									<div class="col-xs-12 noHorizontalPadding">
										<input id="range" class="range" type="range" min="0" max="3" step="1" value="2" data-orientation="horizontal">
										<div class="col-xs-12 noHorizontalPadding vpadding numbs">
											<span class="0">0</span>
											<span class="1">1</span>
											<span class="2 active">2</span>
											<span class="3">Ilimitado</span>
										</div>
									</div>
								</div>
								<div class="col-xs-12 vpadding rw">
									<span class="col-xs-12 regular noHorizontalPadding text-left"># Usuarios</span>
									<div class="col-xs-12 noHorizontalPadding">
										<input id="range" class="range" type="range" min="0" max="4" step="1" value="2" data-orientation="horizontal">
										<div class="col-xs-12 noHorizontalPadding vpadding numbs">
											<span class="0">0</span>
											<span class="1">3</span>
											<span class="2 active">10</span>
											<span class="3">15</span>
											<span class="4">Ilimitado</span>
										</div>
									</div>
								</div>
								<div class="col-xs-12 vpadding rw">
									<span class="col-xs-12 regular noHorizontalPadding text-left"># Usuarios</span>
									<div class="col-xs-12 noHorizontalPadding">
										<input id="range" class="range" type="range" min="0" max="6" step="1" value="2" data-orientation="horizontal">
										<div class="col-xs-12 noHorizontalPadding vpadding numbs">
											<span class="0">0</span>
											<span class="1">100</span>
											<span class="2">500</span>
											<span class="3 active">1000</span>
											<span class="4">1500</span>
											<span class="5">3000</span>
											<span class="6">Ilimitado</span>
										</div>
									</div>
								</div>
								<div class="col-xs-12 noHorizontalPadding vxpadding">
									<div class="col-xs-12 col-sm-6 radios">
										<span class="col-xs-12 regular noHorizontalPadding text-left">Dominio propio</span>
										<div class="col-xs-6">
											<label class="col-xs-12 noHorizontalPadding" for="dominio">Si</label>
											<input type="radio" name="dominio">
										</div>
										<div class="col-xs-6">
											<label class="col-xs-12 noHorizontalPadding" for="dominio">No</label>
											<input type="radio" name="dominio">
										</div>
									</div>
									<div class="col-xs-12 col-sm-6 radios">
										<span class="col-xs-12 regular noHorizontalPadding text-left">Facturación electronica</span>
										<div class="col-xs-6">
											<label class="col-xs-12 noHorizontalPadding" for="facturacion">Si</label>
											<input type="radio" name="facturacion">
										</div>
										<div class="col-xs-6">
											<label class="col-xs-12 noHorizontalPadding" for="facturacion">No</label>
											<input type="radio" name="facturacion">
										</div>
									</div>
								</div>
								<div class="col-xs-12 noHorizontalPadding vxpadding">
									<a href="#" class="btn2 pull-right">PRUEBA GRATIS</a>
									<a href="#" class="btn1 pull-right">CONTRATAR</a>
								</div>
							</div>
						</div>
					</div>
				</div>
				
				<div class="col-xs-12 nopadding text-center item_slide_precio">
					<div class="col-xs-12 nopadding centered">
						<div class="col-xs-12 col-sm-4 start_info">
							<div>
								<div class="col-xs-12 nopadding text-center">
									<img src="assets/img/icons/precios_2/3.svg" alt="" class="col-xs-12 centered">
								</div>
								<h4 class="col-xs-12 noHorizontalPadding regular textRed">ESTANDAR</h4>
								<h3 class="col-xs-12 noHorizontalPadding bold"><small>$</small> 350.00 / <small>Anual</small></h3>
								<ul class="col-xs-12 noHorizontalPadding">
									<li>Punto de venta</li>
									<li>Compras y gastos</li>
									<li>Control de inventario</li>
									<li>Caja y bancos</li>
									<li>Proveedores ( cuentas por pagar )</li>
									<li>Clientes ( cuentas por cobrar )</li>
									<li>Informes en linea</li>
									<li>App de ventas</li>
									<li>Certificado SSL</li>
								</ul>
							</div>
						</div>
						<div class="col-xs-12 col-sm-8 info">
							<div class="vertical">
								<div class="col-xs-12 vpadding rw">
									<span class="col-xs-12 regular noHorizontalPadding text-left"># Sucursales</span>
									<div class="col-xs-12 noHorizontalPadding">
										<input id="range" class="range" type="range" min="0" max="3" step="1" value="2" data-orientation="horizontal">
										<div class="col-xs-12 noHorizontalPadding vpadding numbs">
											<span class="0">0</span>
											<span class="1">1</span>
											<span class="2 active">2</span>
											<span class="3">Ilimitado</span>
										</div>
									</div>
								</div>
								<div class="col-xs-12 vpadding rw">
									<span class="col-xs-12 regular noHorizontalPadding text-left"># Usuarios</span>
									<div class="col-xs-12 noHorizontalPadding">
										<input id="range" class="range" type="range" min="0" max="4" step="1" value="2" data-orientation="horizontal">
										<div class="col-xs-12 noHorizontalPadding vpadding numbs">
											<span class="0">0</span>
											<span class="1">3</span>
											<span class="2 active">10</span>
											<span class="3">15</span>
											<span class="4">Ilimitado</span>
										</div>
									</div>
								</div>
								<div class="col-xs-12 vpadding rw">
									<span class="col-xs-12 regular noHorizontalPadding text-left"># Usuarios</span>
									<div class="col-xs-12 noHorizontalPadding">
										<input id="range" class="range" type="range" min="0" max="6" step="1" value="2" data-orientation="horizontal">
										<div class="col-xs-12 noHorizontalPadding vpadding numbs">
											<span class="0">0</span>
											<span class="1">100</span>
											<span class="2">500</span>
											<span class="3 active">1000</span>
											<span class="4">1500</span>
											<span class="5">3000</span>
											<span class="6">Ilimitado</span>
										</div>
									</div>
								</div>
								<div class="col-xs-12 noHorizontalPadding vxpadding">
									<div class="col-xs-12 col-sm-6 radios">
										<span class="col-xs-12 regular noHorizontalPadding text-left">Dominio propio</span>
										<div class="col-xs-6">
											<label class="col-xs-12 noHorizontalPadding" for="dominio">Si</label>
											<input type="radio" name="dominio">
										</div>
										<div class="col-xs-6">
											<label class="col-xs-12 noHorizontalPadding" for="dominio">No</label>
											<input type="radio" name="dominio">
										</div>
									</div>
									<div class="col-xs-12 col-sm-6 radios">
										<span class="col-xs-12 regular noHorizontalPadding text-left">Facturación electronica</span>
										<div class="col-xs-6">
											<label class="col-xs-12 noHorizontalPadding" for="facturacion">Si</label>
											<input type="radio" name="facturacion">
										</div>
										<div class="col-xs-6">
											<label class="col-xs-12 noHorizontalPadding" for="facturacion">No</label>
											<input type="radio" name="facturacion">
										</div>
									</div>
								</div>
								<div class="col-xs-12 noHorizontalPadding vxpadding">
									<a href="#" class="btn2 pull-right">PRUEBA GRATIS</a>
									<a href="#" class="btn1 pull-right">CONTRATAR</a>
								</div>
							</div>
						</div>
					</div>
				</div>
				
				<div class="col-xs-12 nopadding text-center item_slide_precio">
					<div class="col-xs-12 nopadding centered">
						<div class="col-xs-12 col-sm-4 start_info">
							<div>
								<div class="col-xs-12 nopadding text-center">
									<img src="assets/img/icons/precios_2/4.svg" alt="" class="col-xs-12 centered">
								</div>
								<h4 class="col-xs-12 noHorizontalPadding regular textRed">FULL</h4>
								<h3 class="col-xs-12 noHorizontalPadding bold"><small>$</small> 350.00 / <small>Anual</small></h3>
								<ul class="col-xs-12 noHorizontalPadding">
									<li>Punto de venta</li>
									<li>Compras y gastos</li>
									<li>Control de inventario</li>
									<li>Caja y bancos</li>
									<li>Proveedores ( cuentas por pagar )</li>
									<li>Clientes ( cuentas por cobrar )</li>
									<li>Informes en linea</li>
									<li>App de ventas</li>
									<li>Certificado SSL</li>
								</ul>
							</div>
						</div>
						<div class="col-xs-12 col-sm-8 info">
							<div class="vertical">
								<div class="col-xs-12 vpadding rw">
									<span class="col-xs-12 regular noHorizontalPadding text-left"># Sucursales</span>
									<div class="col-xs-12 noHorizontalPadding">
										<input id="range" class="range" type="range" min="0" max="3" step="1" value="2" data-orientation="horizontal">
										<div class="col-xs-12 noHorizontalPadding vpadding numbs">
											<span class="0">0</span>
											<span class="1">1</span>
											<span class="2 active">2</span>
											<span class="3">Ilimitado</span>
										</div>
									</div>
								</div>
								<div class="col-xs-12 vpadding rw">
									<span class="col-xs-12 regular noHorizontalPadding text-left"># Usuarios</span>
									<div class="col-xs-12 noHorizontalPadding">
										<input id="range" class="range" type="range" min="0" max="4" step="1" value="2" data-orientation="horizontal">
										<div class="col-xs-12 noHorizontalPadding vpadding numbs">
											<span class="0">0</span>
											<span class="1">3</span>
											<span class="2 active">10</span>
											<span class="3">15</span>
											<span class="4">Ilimitado</span>
										</div>
									</div>
								</div>
								<div class="col-xs-12 vpadding rw">
									<span class="col-xs-12 regular noHorizontalPadding text-left"># Usuarios</span>
									<div class="col-xs-12 noHorizontalPadding">
										<input id="range" class="range" type="range" min="0" max="6" step="1" value="2" data-orientation="horizontal">
										<div class="col-xs-12 noHorizontalPadding vpadding numbs">
											<span class="0">0</span>
											<span class="1">100</span>
											<span class="2">500</span>
											<span class="3 active">1000</span>
											<span class="4">1500</span>
											<span class="5">3000</span>
											<span class="6">Ilimitado</span>
										</div>
									</div>
								</div>
								<div class="col-xs-12 noHorizontalPadding vxpadding">
									<div class="col-xs-12 col-sm-6 radios">
										<span class="col-xs-12 regular noHorizontalPadding text-left">Dominio propio</span>
										<div class="col-xs-6">
											<label class="col-xs-12 noHorizontalPadding" for="dominio">Si</label>
											<input type="radio" name="dominio">
										</div>
										<div class="col-xs-6">
											<label class="col-xs-12 noHorizontalPadding" for="dominio">No</label>
											<input type="radio" name="dominio">
										</div>
									</div>
									<div class="col-xs-12 col-sm-6 radios">
										<span class="col-xs-12 regular noHorizontalPadding text-left">Facturación electronica</span>
										<div class="col-xs-6">
											<label class="col-xs-12 noHorizontalPadding" for="facturacion">Si</label>
											<input type="radio" name="facturacion">
										</div>
										<div class="col-xs-6">
											<label class="col-xs-12 noHorizontalPadding" for="facturacion">No</label>
											<input type="radio" name="facturacion">
										</div>
									</div>
								</div>
								<div class="col-xs-12 noHorizontalPadding vxpadding">
									<a href="#" class="btn2 pull-right">PRUEBA GRATIS</a>
									<a href="#" class="btn1 pull-right">CONTRATAR</a>
								</div>
							</div>
						</div>
					</div>
				</div>
				
			</div>
		</div>
	</div>
</section>

<section id="infoContacto">
	<img src="assets/img/infoContacto.svg" alt="" class="backed">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 text-center">
				<div class="col-xs-12 noHorizontalPadding heitheen">
					<h2 class="col-xs-12 nopadding">CONTACTENOS</h2>
				</div>
				<div class="col-xs-12 noHorizontalPadding text-center">
					<div class="figure col-xs-12 noHorizontalPadding centered">
						<a href="#">
							<img src="assets/img/icons/skype_1.svg" alt="">
						</a>
						<a href="#">
							<img src="assets/img/icons/wp_1.svg" alt="">
						</a>
						<a href="#">
							<img src="assets/img/icons/email_1.svg" alt="">
						</a>
					</div>
				</div>
				<div class="col-xs-12 noHorizontalPadding heitheen">
					<h4 class="col-xs-12 noHorizontalPadding nomargin nopaddingTop">Llamenos ahora</h4>
					<h3 class="col-xs-12 nopadding">318 788 3380</h3>
				</div>
			</div>
		</div>
	</div>
</section>

<!-- Modal -->
<div class="modal fade" id="modalVideo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><img src="assets/img/closemodal.svg"></button>
			<div class="modal-body">
				<div class="row">
					<div class="col-xs-12 nopadding text-center" id="video">
					</div>
				</div>
			</div>
		</div>
	</div>
</div>