<section id="slide" class="startSection nopadding">
	<div class="col-xs-12 nopadding item item1">
		<div class="container-fluid">
			<div class="row">
				<div class="col-xs-12 slide">
							<div class="col-xs-12 nopadding">
								<div class="col-xs-12 col-sm-6 text-left noHorizontalPadding heighteen">
									<div class="vertical relative_movile">
										<div class="col-xs-12 text-center">
												<h1 class="col-xs-12 noHorizontalPadding nomargin vxxpadding nopaddingTop regular reveal" style="line-height: 1.2;">Haz tu negocio rentable con nosotros</h1>
												<h3 class="col-xs-12 noHorizontalPadding nomargin vxxpadding nopaddingTop bold reveal">Es hora de hacer crecer tu empresa</h3>
												<h4 class="col-xs-12 noHorizontalPadding nomargin vxxpadding nopaddingTop reveal">SIGA, sistema informático integral para el mejor control de tus ventas, inventario y recursos</h4>
												<div class="col-xs-12 noHorizontalPadding btns_slide">
													<div class="col-xs-12 col-md-4 nopadding text-center reveal">
														<a href="prueba">PRUÉBALO GRATIS</a>
													</div>
													<div class="col-xs-12 col-md-4 nopadding text-center reveal">
														<a href="#contacto" class="scrollTo">CONTÁCTANOS</a>
													</div>
													<div class="col-xs-12 col-md-4 nopadding text-center reveal">
														<a href="https://play.google.com/store/apps/details?id=com.siga2018" target="_blank">
															<svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 81.1 91.9" style="enable-background:new 0 0 81.1 91.9;" xml:space="preserve">
																<g id="surface1">
																	<path d="M4.3,0l43.3,43l11.9-11.9L6.9,0.8C6.1,0.3,5.1,0,4.3,0z M0.6,2C0.2,2.7,0,3.5,0,4.4V88c0,0.7,0.1,1.3,0.4,1.8l44.3-44L0.6,2z M63.1,33.2L50.4,45.8l12.7,12.6l15.5-8.9c2.2-1.3,2.5-2.9,2.5-3.8c0-1.4-0.9-2.8-2.4-3.6C77.3,41.5,67.5,35.8,63.1,33.2z M47.6,48.6L3.9,91.9c0.7,0,1.5-0.2,2.3-0.6c1.7-1,36.3-21,36.3-21l17.1-9.8L47.6,48.6z"/>
																</g>
															</svg>
															<span>
																<small>DISPONIBLE EN</small>
																GOOGLE PLAY
															</span>
														</a>
													</div>
												</div>
										</div>
									</div>
								</div>
								<div class="col-xs-12 col-sm-6 noHorizontalPadding heighteen">
									<div class="vertical relative_movile back_vide_slide">
										<img src="assets/img/video_slide.png" alt="">
												<!-- <div class="col-xs-12 nopadding text-center">
													<svg version="1.1" id="Capa_1" class="play_slide_icon" xmlns:cc="http://creativecommons.org/ns#" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd" xmlns:svg="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 378.8 378.8" style="enable-background:new 0 0 378.8 378.8;" xml:space="preserve">
													<circle class="st0" cx="191.4" cy="185.4" r="175.5"/>
													<g transform="translate(0,-952.36218)">
														<path class="st1" d="M189.4,952.4C85,952.4,0,1037.3,0,1141.8c0,104.5,85,189.4,189.4,189.4s189.4-85,189.4-189.4C378.8,1037.3,293.9,952.4,189.4,952.4L189.4,952.4z M189.4,979.4c89.8,0,162.4,72.5,162.4,162.4c0,89.8-72.5,162.4-162.4,162.4s-162.4-72.5-162.4-162.4C27.1,1052,99.6,979.4,189.4,979.4L189.4,979.4z M141.5,1056.1c-10.4,0.2-19.5,8.6-19.7,20.6v130.1c0.4,16,16.3,25.6,30.3,18l112.7-65.3c6.1-3.6,10.3-10.1,10.3-17.8s-4.2-14.2-10.3-17.8l-112.8-65.3C148.6,1056.9,145,1056,141.5,1056.1L141.5,1056.1z"/>
													</g>
													</svg>
												</div> -->
										</div>
									</div>
								</div>
							</div>
				</div>
			</div>
		</div>
	</div>
	<img src="assets/img/slide_movil.jpg" alt="">
</section>

<section id="sunat" class="backOrange">
	<div class="col-xs-12 noHorizontalPadding text-center div_down">
		<a href="#sunat" class="col-xs-12 noHorizontalPadding centered scrollTo">
			<svg version="1.1" class="bounce" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 365.4 103.2" style="enable-background:new 0 0 365.4 103.2;" xml:space="preserve">
				<polygon points="365.4,22.7 182.7,93.5 0,22.7 0,32.4 182.7,103.2 365.4,32.4 "/>
				<polygon points="365.4,0 182.7,70.8 0,0 0,9.7 182.7,80.5 365.4,9.7 "/>
			</svg>
		</a>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-xs-12 nopadding">
				<h2 class="col-xs-12 noHorizontalPadding vxpadding nopaddingTop nomargin textWhite bold">Lleva tu empresa al siguiente nivel</h2>
				<div class="col-xs-12 noHorizontalPadding text-center">
					<h3 class="col-xs-12 col-md-8 noHorizontalPadding nopadding nomargin textWhite centered">Con SIGA administra, controla y supervisa tu empresa desde donde estés</h3>
				</div>
				<div class="col-xs-12 noHorizontalPadding vxpadding text-center">
					<div class="col-xs-12 centered square">
						<div class="col-xs-12 nopadding text-center">
							<img class="col-xs-12 logo_sunat centered" src="assets/img/icons/sunat/sunat_logo_blanco.png" alt="">
						</div>
						<h4 class="col-xs-12 textWhite">
							Todos los documentos emitidos desde SIGA pueden ser consultados a través del portal web de la SUNAT
						</h4>
					</div>
				</div>
				<div class="col-xs-12 noHorizontalPadding sunat_items">
					<div class="col-xs-6 col-sm-3 nopadding text-center item">
						<div class="col-xs-12 centered">
								<div class="col-xs-12 noHorizontalPadding text-center">
									<a href="#" class="col-xs-12 centered noHorizontalPadding">
										<img class="col-xs-12 noHorizontalPadding" src="assets/img/icons/sunat/facturacion_elec.svg" alt="">
									</a>
								</div>
								<h3 class="col-xs-12 textWhite">FACTURACIÓN ELECTRONICA</h3>
								<p class="col-xs-12 textWhite">Con SIGA administra, controla y supervisa tu empresa desde donde estés</p>
						</div>
					</div>
					<div class="col-xs-6 col-sm-3 nopadding text-center item">
						<div class="col-xs-12 centered">
								<div class="col-xs-12 noHorizontalPadding text-center">
									<a href="#" class="col-xs-12 centered noHorizontalPadding">
										<img class="col-xs-12 noHorizontalPadding" src="assets/img/icons/sunat/app_movil.svg" alt="">
									</a>
								</div>
								<h3 class="col-xs-12 textWhite">APLICATIVO MOVIL</h3>
								<p class="col-xs-12 textWhite">Tus ventas no paran, SIGA tampoco. Descarga la APP y realiza ventas las 24 hrs.</p>
						</div>
					</div>
					<div class="col-xs-6 col-sm-3 nopadding text-center item">
						<div class="col-xs-12 centered">
								<div class="col-xs-12 noHorizontalPadding text-center">
									<a href="#" class="col-xs-12 centered noHorizontalPadding">
										<img class="col-xs-12 noHorizontalPadding" src="assets/img/icons/sunat/ecommerce.svg" alt="">
									</a>
								</div>
								<h3 class="col-xs-12 textWhite">ECOMMERCE/ TIENDA ONLINE</h3>
								<p class="col-xs-12 textWhite">Vende por internet fácil y rápido, con una plataforma completamente integrada.</p>
						</div>
					</div>
					<div class="col-xs-6 col-sm-3 nopadding text-center item">
						<div class="col-xs-12 centered">
								<div class="col-xs-12 noHorizontalPadding text-center">
									<a href="#" class="col-xs-12 centered noHorizontalPadding">
										<img class="col-xs-12 noHorizontalPadding" src="assets/img/icons/sunat/reportes.svg" alt="">
									</a>
								</div>
								<h3 class="col-xs-12 textWhite">REPORTES EN LINEA</h3>
								<p class="col-xs-12 textWhite">Conoce el estado de tu negocio en tiempo real y toma las mejores decisiones para impulsar tu empresa.</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<section id="facil_eficiente" class="parallax_dev" data-parallax="scroll" data-position="center center" data-bleed="1" data-natural-width="1920" data-natural-height="835" data-image-src="assets/img/facil_rapido_eficient.jpg">
	<div class="container">
		<div class="row">
      <div class="col-xs-12 noHorizontalPadding">
        <div class="col-xs-12 col-sm-6 pull-right text-right back_transparent">
          <h1 class="col-xs-12 noHorizontalPadding nomarginTop textBlue">Fácil, rápido y eficiente</h1>
          <h4 class="col-xs-12 noHorizontalPadding nomarginTop bold">Con SIGA App podrás vender en cualquier lugar y en cualquiero momento</h4>
          <div class="col-xs-12 noHorizontalPadding vpadding eficiences">
						<div class="col-xs-6 col-sm-3 item text-center">
              <div class="col-xs-12 noHorizontalPadding centered">
                <img src="assets/img/icons/rapido_eficiente/ventas.svg" alt="" class="col-xs-12 noHorizontalPadding">
                <span class="col-xs-12 noHorizontalPadding">Ventas</span>
              </div>
            </div>
						<div class="col-xs-6 col-sm-3 item text-center">
              <div class="col-xs-12 noHorizontalPadding centered">
                <img src="assets/img/icons/rapido_eficiente/clientes.svg" alt="" class="col-xs-12 noHorizontalPadding">
                <span class="col-xs-12 noHorizontalPadding">Clientes</span>
              </div>
            </div>
						<div class="col-xs-6 col-sm-3 item text-center">
              <div class="col-xs-12 noHorizontalPadding centered">
                <img src="assets/img/icons/rapido_eficiente/inventario.svg" alt="" class="col-xs-12 noHorizontalPadding">
                <span class="col-xs-12 noHorizontalPadding">Inventario</span>
              </div>
            </div>
						<div class="col-xs-6 col-sm-3 item text-center">
              <div class="col-xs-12 noHorizontalPadding centered">
                <img src="assets/img/icons/rapido_eficiente/reportes.svg" alt="" class="col-xs-12 noHorizontalPadding">
                <span class="col-xs-12 noHorizontalPadding">Reportes de Ventas diarias</span>
              </div>
            </div>
          </div>
					<div class="col-xs-12 noHorizontalPadding">
						<a href="https://play.google.com/store/apps/details?id=com.siga2018" target="_blank" class="btn_gplay">
							<img src="assets/img/icons/rapido_eficiente/google-play.png" alt="" class="col-xs-12 noHorizontalPadding">
						</a>
					</div>
        </div>
      </div>
		</div>
	</div>
</section>

<section id="contactanos_ahora" class="nopaddingBottom">
	<div class="container">
		<div class="row">
      <div class="col-xs-12 noHorizontalPadding">
        <div class="col-xs-12 text-center">
          <h1 class="col-xs-12 noHorizontalPadding nomarginTop textOrange">Contáctanos ahora</h1>
          <h4 class="col-xs-12 noHorizontalPadding nomarginTop bold">Cómo quieres comunicarte con nosotros?</h4>
					<div class="col-xs-12 noHorizontalPadding vpadding text-center">
						<div class="col-xs-12 col-sm-12 col-md-10 col-lg-9 noHorizontalPadding centered">

							<div class="col-xs-12 col-md-4 noHorizontalPadding text-center">
								<a href="https://api.whatsapp.com/send?phone=513939907" target="_blank" class="centered btn_contacto_rap whats">
									<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 229.4 229.4" style="enable-background:new 0 0 229.4 229.4;" xml:space="preserve">
										<g>
											<g>
												<path class="white_fill" d="M229.4,111.7c0,61.7-50.4,111.7-112.6,111.7c-19.7,0-38.3-5-54.4-13.9L0,229.4l20.3-59.9C10,152.7,4.1,132.9,4.1,111.8C4.2,50,54.6,0,116.8,0S229.4,50,229.4,111.7L229.4,111.7z M116.8,17.8c-52.2,0-94.7,42.1-94.7,93.9c0,20.5,6.7,39.6,18,55.1l-11.8,34.9l36.4-11.6c14.9,9.8,32.9,15.5,52.1,15.5c52.2,0,94.7-42.1,94.7-93.9C211.4,59.9,169,17.8,116.8,17.8L116.8,17.8z M173.6,137.5c-0.7-1.1-2.5-1.8-5.3-3.2s-16.3-8-18.9-8.9c-2.5-0.9-4.4-1.4-6.2,1.4c-1.8,2.7-7.1,8.9-8.7,10.7c-1.6,1.8-3.2,2.1-6,0.7c-2.8-1.4-11.7-4.3-22.2-13.6c-8.2-7.3-13.7-16.2-15.4-19c-1.6-2.7-0.2-4.2,1.2-5.6c1.2-1.2,2.8-3.2,4.1-4.8c1.4-1.6,1.8-2.8,2.8-4.6c0.9-1.8,0.5-3.4-0.2-4.8S92.6,71,90.3,65.5C88.1,60,85.8,61,84.1,61c-1.6,0-3.4-0.2-5.3-0.2c-1.8,0-4.8,0.7-7.4,3.4c-2.5,2.7-9.7,9.4-9.7,22.8c0,13.5,9.9,26.5,11.3,28.3s19.1,30.4,47.2,41.4c28.1,11,28.1,7.3,33.1,6.8c5.1-0.4,16.3-6.6,18.6-13C174.3,144.1,174.3,138.6,173.6,137.5L173.6,137.5z"/>
											</g>
										</g>
									</svg>
									<span>WHATSAPP</span>
								</a>
							</div>

							<div class="col-xs-12 col-md-4 noHorizontalPadding text-center">
								<a href="mailto: ventas@siga.com.pe" class="centered btn_contacto_rap email">
									<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 229.4 229.4" style="enable-background:new 0 0 229.4 229.4;" xml:space="preserve">
										<g transform="translate(0,-952.36218)">
											<path class="white_fill" d="M30.4,988c-15.9,0-29,13.1-29,29v100.1c0,15.9,13.1,29,29,29H199c15.9,0,29-13.1,29-29V1017c0-15.9-13.1-29-29-29H30.4z M30.4,1003.8H199c1.3,0,2.5,0.2,3.7,0.5l-85.5,80.3c-0.9,0.9-4,0.9-4.9,0l-85.5-80.3C27.9,1004,29.1,1003.8,30.4,1003.8z M17.2,1017.2l56.2,52.8l-56,49.8c-0.2-0.8-0.2-1.7-0.2-2.6L17.2,1017.2L17.2,1017.2z M212.2,1017.2v99.9c0,0.9-0.1,1.8-0.2,2.6l-56-49.8L212.2,1017.2L212.2,1017.2z M85.1,1080.8l16.3,15.3c7.6,7.1,19.1,7.1,26.7,0l16.3-15.3l55.6,49.4c-0.3,0-0.6,0.1-0.9,0.1H30.4c-0.3,0-0.6-0.1-0.9-0.1L85.1,1080.8L85.1,1080.8z"/>
										</g>
									</svg>
									<span>E-MAIL</span>
								</a>
							</div>

							<div class="col-xs-12 col-md-4 noHorizontalPadding text-center">
								<a href="tel:+51013939907" class="centered btn_contacto_rap llamada">
									<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 229.4 229.4" style="enable-background:new 0 0 229.4 229.4;" xml:space="preserve">
										<g>
											<path class="white_fill" d="M60,171c25.9,25.9,57,44.7,87.4,52.4c6.5,1.9,16.2,2.6,23.9,3.2c7.8,0.6,14.9-3.2,18.8-9.7l17.5-27.2c4.5-7.1,1.9-16.2-5.2-20.1l-42.1-22c-5.8-3.2-12.9-1.3-17.5,3.9l-15.5,20.1c-14.9-8.4-26.5-15.5-39.5-29.1c-14.2-14.2-21.4-25.9-29.1-40.1l19.4-15.5c5.2-3.9,7.1-11.6,3.9-17.5L60.7,27.3c-3.9-7.1-12.9-9.7-20.1-5.2L14.1,40.3C7.6,44.2,4.3,51.3,5,59C5.6,66.8,6.3,76.5,8.2,83C15.4,114.1,34.1,145.1,60,171z"/>
											<path class="white_fill" d="M117.6,90.8c5.2,1.3,10.4,4.5,14.2,8.4c3.9,3.9,7.1,9.1,8.4,14.2c1.3,4.5,5.2,7.1,9.7,7.1h0.6c6.5,0,10.4-6.5,9.1-12.3c-2.6-8.4-7.1-16.8-13.6-23.3s-14.9-11-23.3-13.6c-5.8-1.9-11.6,2.6-12.3,9.1V81C110.5,85.6,113.1,90.1,117.6,90.8z"/>
											<path class="white_fill" d="M120.2,57.1c12.9,2.6,25.2,8.4,35.6,18.8s16.2,22.7,18.8,35.6c0.6,4.5,5.2,8.4,10.4,7.8h0.6c5.8,0,10.4-5.8,9.1-11.6c-3.2-16.8-11-33-23.9-46.6c-12.9-13.6-29.1-21.4-46.6-23.9c-5.8-1.3-11,3.2-11.6,9.1v0.6C111.8,51.9,115.7,56.5,120.2,57.1z"/>
											<path class="white_fill" d="M194,37C174.6,17.6,150.6,6,125.4,2.7c-5.8-0.6-11,3.2-11,9.1v0.6c0,5.2,3.2,9.1,8.4,10.4c20.7,3.2,41.4,12.3,57,28.5s25.2,36.2,28.5,57c0.6,5.2,5.2,9.1,10.4,8.4h0.6c5.8,0,9.7-5.2,9.1-11C225,81,213.4,56.5,194,37z"/>
										</g>
									</svg>
									<span>LLAMADA</span>
								</a>
							</div>

						</div>
					</div>
					<h4 class="col-xs-12 noHorizontalPadding nomarginTop bold text-center">Prefieres una visita? Agéndala hoy</h4>
					<div class="col-xs-12 noHorizontalPadding text-center">
						<a href="#contacto" class="btn5 scrollTo centered">AGENDAR VISITA</a>
					</div>
        </div>
      </div>
		</div>
	</div>
</section>



<section id="testimonios-clientes">
	<div class="container-fluid nopadding">
		<div class="row">
			<div class="col-xs-12 nopadding">
				<h2 class="col-xs-12 noHorizontalPadding vxpadding nopaddingTop nomargin">Conoce las empresas que ya están alcanzando el éxito</h2>
				<div class="col-xs-12 nopadding" id="slide_testimonios">

					<div class="col-xs-12 col-md-6 col-lg-4 noHorizontalPadding text-center item_testimonio_2">
						<div class="col-xs-12 nopadding centered">
							<div class="col-xs-12 nopadding img">
								<img class="col-xs-12 nopadding" src="assets/img/testimonios/1.jpg" alt="">
								<h5>Luisa Sifuentes - MHUSA<small>Accesorios y bisutería</small></h5>
							</div>
							<div class="col-xs-12 text-left info">
								<div class="vertical relative_movile">
									<div class="col-xs-12 info_mid">
										<div class="col-xs-12 noHorizontalPadding">
											<p class="open light">Con SIGA puedo ver el stock de cualquiera de mis sucursales, y lo mejor de todo es que si en la tienda 1 tengo 50 unidades y en la tienda 2 tengo 200 unidades, puedo vender las 250 unidades, priorizando los negocios y ganando ventas.</p>
											<div class="col-xs-12 noHorizontalPadding" style="margin-top: 10px;">
												<a href="#" id="video_tes1">
													<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 360.8 360.8" style="enable-background:new 0 0 360.8 360.8;" xml:space="preserve">
														<g>
															<polygon points="135.3,115 135.3,245.8 245.3,180.4 	"/>
															<path d="M282.3,0H78.5C35.2,0,0,35.2,0,78.5v203.9c0,43.3,35.2,78.5,78.5,78.5h203.9c43.3,0,78.5-35.2,78.5-78.5V78.5C360.8,35.2,325.6,0,282.3,0z M117.3,277.4V83.4l163.3,97L117.3,277.4z"/>
														</g>
													</svg>
													<span>Ver video</span>
												</a>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>

					<div class="col-xs-12 col-md-6 col-lg-4 noHorizontalPadding text-center item_testimonio_2">
						<div class="col-xs-12 nopadding centered">
							<div class="col-xs-12 nopadding img">
								<img class="col-xs-12 nopadding" src="assets/img/testimonios/2.jpg" alt="">
								<h5>David Hernández - LEVELSTORE<small>Tienda On Line</small></h5>
							</div>
							<div class="col-xs-12 text-left info">
								<div class="vertical relative_movile">
									<div class="col-xs-12 info_mid">
										<div class="col-xs-12 noHorizontalPadding">
											<p class="open light">SIGA me permite promover ventas en mayor volumen, si el cliente venía a comprarme 10 unidades, puedo ofrecerle el 5% de descuento si compra 20, es muy práctico porque se aplica por producto.</p>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>

					<div class="col-xs-12 col-md-6 col-lg-4 noHorizontalPadding text-center item_testimonio_2">
						<div class="col-xs-12 nopadding centered">
							<div class="col-xs-12 nopadding img">
								<img class="col-xs-12 nopadding" src="assets/img/testimonios/3.jpg" alt="">
								<h5>María Huanca - JCV THE BEST<small>Ferretería</small></h5>
							</div>
							<div class="col-xs-12 text-left info">
								<div class="vertical relative_movile">
									<div class="col-xs-12 info_mid">
										<div class="col-xs-12 noHorizontalPadding">
											<p class="open light">Con SIGA puedo llevar la cuenta de mis proveedores, o mis clientes a través del sistema puedo generar un cronograma de pagos, diario, interdiario, semanal, mensual o personalizado, y así saber qué días debo pagar.</p>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>

				</div>
			</div>
			<div class="col-xs-12 noHorizontalPadding vpadding text-center">
				<a href="prueba" class="btn3 centered">QUIERO MI PRUEBA GRATIS</a>
			</div>
		</div>
	</div>
</section>




<section id="planes" class="">
	<div class="container">
		<div class="row">
      <div class="col-xs-12 noHorizontalPadding">
        <div class="col-xs-12 text-center">
          <h1 class="col-xs-12 noHorizontalPadding nomarginTop textBlue">Planes</h1>
          <div class="col-xs-12 noHorizontalPadding text-center">
          	<h4 class="col-xs-12 col-sm-10 col-md-9 noHorizontalPadding nomarginTop centered">Nuestro servicio incluye soporte y asistencia permanente, no tenemos precios ocultos. Elige le plan que mejor se acomode a tu negocio.</h4>
          </div>
					<div class="col-xs-12 noHorizontalPadding vpadding text-center planes_items">

						<div class="col-xs-12 col-md-4 noHorizontalPadding text-center item">
							<div class="col-xs-12 centered">
								<div class="col-xs-12 noHorizontalPadding title">
									<div class="vertical">
										<div class="col-xs-12 noHorizontalPadding">
											<h1 class="col-xs-12 noHorizontalPadding nomargin textWhite">SIGA EXPERT</h1>
											<span class="col-xs-12 noHorizontalPadding textWhite">RECOMENDADO</span>
										</div>
									</div>
								</div>
								<div class="col-xs-12 info">
										<ul>
											<li>Facturación y boleta eletrónica</li>
											<li>Aplicativo de ventas</li>
											<li>Capacitaciones</li>
											<li>Soporte remoto / presencial</li>
											<li>6 Almacenes</li>
											<li>Kardex</li>
											<li>Convertir cotización a ventas</li>
											<li>Control de movimientos bancarios</li>
											<li>2 Sucursales</li>
											<li>E-commerce</li>
										</ul>
								</div>
								<div class="col-xs-12 noHorizontalPadding vpadding text-center btns">
									<div class="col-xs-12 noHorizontalPadding centered">
										<a href="#" class="blue">
											<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 451 451" style="enable-background:new 0 0 451 451;" xml:space="preserve">
												<path class="white_fill" d="M175.1,336.4C86.7,336.9,14.6,265.6,14,177.1S84.8,16.5,173.3,16s160.6,70.8,161.1,159.3c0,0.3,0,0.6,0,0.9C334.6,264.3,263.3,336,175.1,336.4z M175.1,58.5c-65-0.6-118.1,51.7-118.7,116.7s51.7,118.1,116.7,118.7c65,0.6,118.1-51.7,118.7-116.7c0-0.3,0-0.7,0-1C292,111.5,239.8,58.9,175.1,58.5L175.1,58.5z"/>
												<rect x="325.3" y="243.3" transform="matrix(0.7056 -0.7086 0.7086 0.7056 -143.7732 347.709)" class="white_fill" width="42.5" height="207.1"/>
											</svg>
											<span>VER MÀS</span>
										</a>
										<a href="#" class="green">
											<svg version="1.1" xmlns:cc="http://creativecommons.org/ns#" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd" xmlns:svg="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 451 451" style="enable-background:new 0 0 451 451;" xml:space="preserve">
												<g transform="translate(0,-952.36218)">
													<path class="white_fill" d="M22.5,984.5C14.5,984.5,8,991,8,999c0,8,6.5,14.5,14.5,14.5h46.2l49.9,235.3c2,8.9,7.8,16.2,15.1,16.2h241.8c7.7,0.1,14.7-6.8,14.7-14.5s-7-14.6-14.7-14.5h-230l-6.2-29h255.5c6.5,0,12.6-5,14.1-11.3l33.8-145.1c1.9-8.4-5.4-17.6-14.1-17.7H102.6l-7.9-36.9c-1.4-6.4-7.6-11.5-14.2-11.5H22.5z M108.6,1061.8h301.7l-27,116H133.3L108.6,1061.8z M182.1,1274.6c-26.5,0-48.4,21.8-48.4,48.4c0,26.5,21.8,48.4,48.4,48.4s48.4-21.8,48.4-48.4C230.4,1296.4,208.6,1274.6,182.1,1274.6z M327.1,1274.6c-26.5,0-48.4,21.8-48.4,48.4c0,26.5,21.8,48.4,48.4,48.4c26.5,0,48.4-21.8,48.4-48.4C375.5,1296.4,353.6,1274.6,327.1,1274.6z M182.1,1303.6c10.9,0,19.3,8.5,19.3,19.3c0,10.9-8.5,19.3-19.3,19.3c-10.9,0-19.3-8.5-19.3-19.3C162.7,1312.1,171.2,1303.6,182.1,1303.6z M327.1,1303.6c10.9,0,19.3,8.5,19.3,19.3c0,10.9-8.5,19.3-19.3,19.3c-10.9,0-19.3-8.5-19.3-19.3C307.8,1312.1,316.3,1303.6,327.1,1303.6z"/>
												</g>
											</svg>
											<span>CONTRATAR</span>
										</a>
									</div>
								</div>
							</div>
						</div>

						<div class="col-xs-12 col-md-4 noHorizontalPadding text-center item light">
							<div class="col-xs-12 centered">
								<div class="col-xs-12 noHorizontalPadding title">
									<div class="vertical">
										<div class="col-xs-12 noHorizontalPadding">
											<h1 class="col-xs-12 noHorizontalPadding nomargin textWhite">SIGA ESTÁNDAR</h1>
										</div>
									</div>
								</div>
								<div class="col-xs-12 info">
										<ul>
											<li>Facturación y boleta eletrónica</li>
											<li>Aplicativo de ventas</li>
											<li>Capacitaciones</li>
											<li>Soporte remoto / presencial</li>
											<li>4 Almacenes</li>
											<li>Kardex</li>
											<li>Convertir cotización a ventas</li>
											<li>Control de movimientos bancarios</li>
											<li>1 Sucursal</li>
											<li class="red">E-commerce</li>
										</ul>
								</div>
								<div class="col-xs-12 noHorizontalPadding vpadding text-center btns">
									<div class="col-xs-12 noHorizontalPadding centered">
										<a href="#" class="blue">
											<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 451 451" style="enable-background:new 0 0 451 451;" xml:space="preserve">
												<path class="white_fill" d="M175.1,336.4C86.7,336.9,14.6,265.6,14,177.1S84.8,16.5,173.3,16s160.6,70.8,161.1,159.3c0,0.3,0,0.6,0,0.9C334.6,264.3,263.3,336,175.1,336.4z M175.1,58.5c-65-0.6-118.1,51.7-118.7,116.7s51.7,118.1,116.7,118.7c65,0.6,118.1-51.7,118.7-116.7c0-0.3,0-0.7,0-1C292,111.5,239.8,58.9,175.1,58.5L175.1,58.5z"/>
												<rect x="325.3" y="243.3" transform="matrix(0.7056 -0.7086 0.7086 0.7056 -143.7732 347.709)" class="white_fill" width="42.5" height="207.1"/>
											</svg>
											<span>VER MÀS</span>
										</a>
										<a href="#" class="green">
											<svg version="1.1" xmlns:cc="http://creativecommons.org/ns#" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd" xmlns:svg="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 451 451" style="enable-background:new 0 0 451 451;" xml:space="preserve">
												<g transform="translate(0,-952.36218)">
													<path class="white_fill" d="M22.5,984.5C14.5,984.5,8,991,8,999c0,8,6.5,14.5,14.5,14.5h46.2l49.9,235.3c2,8.9,7.8,16.2,15.1,16.2h241.8c7.7,0.1,14.7-6.8,14.7-14.5s-7-14.6-14.7-14.5h-230l-6.2-29h255.5c6.5,0,12.6-5,14.1-11.3l33.8-145.1c1.9-8.4-5.4-17.6-14.1-17.7H102.6l-7.9-36.9c-1.4-6.4-7.6-11.5-14.2-11.5H22.5z M108.6,1061.8h301.7l-27,116H133.3L108.6,1061.8z M182.1,1274.6c-26.5,0-48.4,21.8-48.4,48.4c0,26.5,21.8,48.4,48.4,48.4s48.4-21.8,48.4-48.4C230.4,1296.4,208.6,1274.6,182.1,1274.6z M327.1,1274.6c-26.5,0-48.4,21.8-48.4,48.4c0,26.5,21.8,48.4,48.4,48.4c26.5,0,48.4-21.8,48.4-48.4C375.5,1296.4,353.6,1274.6,327.1,1274.6z M182.1,1303.6c10.9,0,19.3,8.5,19.3,19.3c0,10.9-8.5,19.3-19.3,19.3c-10.9,0-19.3-8.5-19.3-19.3C162.7,1312.1,171.2,1303.6,182.1,1303.6z M327.1,1303.6c10.9,0,19.3,8.5,19.3,19.3c0,10.9-8.5,19.3-19.3,19.3c-10.9,0-19.3-8.5-19.3-19.3C307.8,1312.1,316.3,1303.6,327.1,1303.6z"/>
												</g>
											</svg>
											<span>CONTRATAR</span>
										</a>
									</div>
								</div>
							</div>
						</div>

						<div class="col-xs-12 col-md-4 noHorizontalPadding text-center item light">
							<div class="col-xs-12 centered">
								<div class="col-xs-12 noHorizontalPadding title">
									<div class="vertical">
										<div class="col-xs-12 noHorizontalPadding">
											<h1 class="col-xs-12 noHorizontalPadding nomargin textWhite">SIGA BASIC</h1>
										</div>
									</div>
								</div>
								<div class="col-xs-12 info">
										<ul>
											<li>Facturación y boleta eletrónica</li>
											<li>Aplicativo de ventas</li>
											<li>Capacitaciones</li>
											<li>Soporte remoto / presencial</li>
											<li>1 Almacen</li>
											<li class="red">Kardex</li>
											<li class="red">Convertir cotización a ventas</li>
											<li class="red">Control de movimientos bancarios</li>
											<li class="red">1 Sucursal</li>
											<li class="red">E-commerce</li>
										</ul>
								</div>
								<div class="col-xs-12 noHorizontalPadding vpadding text-center btns">
									<div class="col-xs-12 noHorizontalPadding centered">
										<a href="#" class="blue">
											<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 451 451" style="enable-background:new 0 0 451 451;" xml:space="preserve">
												<path class="white_fill" d="M175.1,336.4C86.7,336.9,14.6,265.6,14,177.1S84.8,16.5,173.3,16s160.6,70.8,161.1,159.3c0,0.3,0,0.6,0,0.9C334.6,264.3,263.3,336,175.1,336.4z M175.1,58.5c-65-0.6-118.1,51.7-118.7,116.7s51.7,118.1,116.7,118.7c65,0.6,118.1-51.7,118.7-116.7c0-0.3,0-0.7,0-1C292,111.5,239.8,58.9,175.1,58.5L175.1,58.5z"/>
												<rect x="325.3" y="243.3" transform="matrix(0.7056 -0.7086 0.7086 0.7056 -143.7732 347.709)" class="white_fill" width="42.5" height="207.1"/>
											</svg>
											<span>VER MÀS</span>
										</a>
										<a href="#" class="green">
											<svg version="1.1" xmlns:cc="http://creativecommons.org/ns#" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd" xmlns:svg="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 451 451" style="enable-background:new 0 0 451 451;" xml:space="preserve">
												<g transform="translate(0,-952.36218)">
													<path class="white_fill" d="M22.5,984.5C14.5,984.5,8,991,8,999c0,8,6.5,14.5,14.5,14.5h46.2l49.9,235.3c2,8.9,7.8,16.2,15.1,16.2h241.8c7.7,0.1,14.7-6.8,14.7-14.5s-7-14.6-14.7-14.5h-230l-6.2-29h255.5c6.5,0,12.6-5,14.1-11.3l33.8-145.1c1.9-8.4-5.4-17.6-14.1-17.7H102.6l-7.9-36.9c-1.4-6.4-7.6-11.5-14.2-11.5H22.5z M108.6,1061.8h301.7l-27,116H133.3L108.6,1061.8z M182.1,1274.6c-26.5,0-48.4,21.8-48.4,48.4c0,26.5,21.8,48.4,48.4,48.4s48.4-21.8,48.4-48.4C230.4,1296.4,208.6,1274.6,182.1,1274.6z M327.1,1274.6c-26.5,0-48.4,21.8-48.4,48.4c0,26.5,21.8,48.4,48.4,48.4c26.5,0,48.4-21.8,48.4-48.4C375.5,1296.4,353.6,1274.6,327.1,1274.6z M182.1,1303.6c10.9,0,19.3,8.5,19.3,19.3c0,10.9-8.5,19.3-19.3,19.3c-10.9,0-19.3-8.5-19.3-19.3C162.7,1312.1,171.2,1303.6,182.1,1303.6z M327.1,1303.6c10.9,0,19.3,8.5,19.3,19.3c0,10.9-8.5,19.3-19.3,19.3c-10.9,0-19.3-8.5-19.3-19.3C307.8,1312.1,316.3,1303.6,327.1,1303.6z"/>
												</g>
											</svg>
											<span>CONTRATAR</span>
										</a>
									</div>
								</div>
							</div>
						</div>

					</div>
        </div>
      </div>
		</div>
	</div>
</section>


<section id="equipos" class="nopadding">
	<div class="container">
		<div class="row">
      <div class="col-xs-12 noHorizontalPadding">
        <div class="col-xs-12 text-center">
					<h1 class="col-xs-12 noHorizontalPadding nomarginTop textOrange">Necesitas los equipos? <small class="textOrange">Nosotros te ayudamos</small></h1>
					<h3 class="col-xs-12 noHorizontalPadding nomarginTop">Tenemos los suministros y equipos que necesitas para alcanzar el éxito</h3>
          <div class="col-xs-12 noHorizontalPadding vpadding text-center">
							<a href="#" class="btn2 biggest centered" id="send_contacto_empresa">COTIZAR</a>
          </div>
					<div class="col-xs-12 noHorizontalPadding text-center">
						<img src="assets/img/EQUIPOS.jpg" alt="" class="col-xs-12 col-sm-11 col-md-10 noHorizontalPadding centered">
					</div>
        </div>
      </div>
		</div>
	</div>
</section>


<!--
<section id="beneficios-siga" class="backBlue">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 nopadding">
				<h2 class="col-xs-12 noHorizontalPadding vxpadding nopaddingTop nomargin">¿ Como me beneficia SIGA ?</h2>
				<div class="col-xs-12 col-sm-6 item text-center">
					<div class="col-xs-12 centered">
						<img src="assets/img/beneficio1.svg" alt="">
						<div class="vertical end">
							<div class="col-xs-12 text-left">
								<span class="textWhite">Finanzas</span>
								<h5 class="col-xs-12 noHorizontalPadding text-uppercase bold">Manejo completo de finanzas</h5>
								<p class="col-xs-12 noHorizontalPadding">Conoce el diario de ventas, pago a proveedores, gastos del día a día, tus pagos de prestamos y más</p>
							</div>
						</div>
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 item text-center">
					<div class="col-xs-12 centered">
						<img src="assets/img/beneficio2.svg" alt="">
						<div class="vertical end">
							<div class="col-xs-12 text-left">
								<span class="textWhite">INVENTARIO</span>
								<h5 class="col-xs-12 noHorizontalPadding text-uppercase bold">Inventario centralizado</h5>
								<p class="col-xs-12 noHorizontalPadding">Consulta tu inventario agrupado por todos tus almacenes, detallado por almacen o realiza comparativos de inventario entre almacenes</p>
							</div>
						</div>
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 item text-center">
					<div class="col-xs-12 centered">
						<img src="assets/img/beneficio3.svg" alt="">
						<div class="vertical end">
							<div class="col-xs-12 text-left">
								<span class="textWhite">VENTAS</span>
								<h5 class="col-xs-12 noHorizontalPadding text-uppercase bold">APP DE VENTAS</h5>
								<p class="col-xs-12 noHorizontalPadding">Ahorra espacio y dinero en la compra de computadoras para tus puntos de venta, podras crear clientes y realizar ventas desde el app de ventas</p>
							</div>
						</div>
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 item text-center">
					<div class="col-xs-12 centered">
						<img src="assets/img/beneficio4.svg" alt="">
						<div class="vertical end">
							<div class="col-xs-12 text-left">
								<span class="textWhite">Seguridad</span>
								<h5 class="col-xs-12 noHorizontalPadding text-uppercase bold">Información segura y siempre disponible</h5>
								<p class="col-xs-12 noHorizontalPadding">Nuestro sistema es web y nos encontramos alojado en la nube de azure lo que nos asegura y brinda un alto grado de confiabilidad</p>
							</div>
						</div>
					</div>
				</div>
				<div class="col-xs-12 noHorizontalPadding vxpadding text-center">
					<a href="beneficios" class="btn2 centered">VER MÁS</a>
				</div>
				<div class="col-xs-12 noHorizontalPadding vpadding text-center">
					<p class="col-xs-12 col-sm-10 col-md-8 nopadding centered">No necesitas de instalaciones ni adquirir equipos de alto costo, ademas contaras con soporte y asistencia permanente</p>
					<p class="col-xs-12 col-sm-10 col-md-8 nopadding centered">SIGA, es un sistema de control y gestíon interno</p>
				</div>
			</div>
		</div>
	</div>
</section>

<section id="postventa" class="backBlue">
	<img src="assets/img/postventa.svg" alt="">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 nopadding">
				<div class="col-xs-12 col-sm-6 nopadding text-center">
					<div class="col-xs-12 centered box">
						<div class="col-xs-12 noHorizontalPadding">
							<img src="assets/img/icons/postventa1.svg" alt="">
							<div class="col-xs-12 nopadding lined"></div>
							<div class="col-xs-12 noHorizontalPadding vpadding nopaddingTop text">
								<span class="pull-left">Usuarios</span>
								<span class="pull-right">120</span>
							</div>
							<div class="col-xs-12 nopadding metric">
								<div class="col-xs-4 nopadding"></div>
							</div>
						</div>
						<div class="col-xs-12 noHorizontalPadding">
							<img src="assets/img/icons/postventa2.svg" alt="">
							<div class="col-xs-12 nopadding lined"></div>
							<div class="col-xs-12 noHorizontalPadding vpadding nopaddingTop text">
								<span class="pull-left">Sucursales con SIGA</span>
								<span class="pull-right">250</span>
							</div>
							<div class="col-xs-12 nopadding metric">
								<div class="col-xs-8 nopadding"></div>
							</div>
						</div>
						<div class="col-xs-12 noHorizontalPadding">
							<img src="assets/img/icons/postventa3.svg" alt="">
							<div class="col-xs-12 nopadding lined"></div>
							<div class="col-xs-12 noHorizontalPadding vpadding nopaddingTop text">
								<span class="pull-left">Ventas realizadas con iCloudP</span>
								<span class="pull-right">1300</span>
							</div>
							<div class="col-xs-12 nopadding metric">
								<div class="col-xs-10 nopadding"></div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 nopadding text-center contentPlay">
					<img src="assets/img/postventa1.svg" alt="">
					<div class="vertical">
						<div class="col-xs-12 nopadding">
							<h3 class="col-xs-12 col-sm-10 col-md-8 nopadding centered">Nuestro mejor servicio <strong>es la post-venta</strong></h3>
							<div class="col-xs-12 nopadding text-center">
								<img src="assets/img/play.svg" alt="" class="col-xs-12 centered">
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<section id="testimonios" class="backBlue">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 nopadding">
				<h2 class="col-xs-12 noHorizontalPadding vxpadding nopaddingTop nomargin">Lo que dicen nuestros clientes</h2>
				<div class="col-xs-12 nopadding" id="slideTestimonios">
					<div class="col-xs-12 col-md-6 text-center nopadding item">
						<div class="col-xs-12 text-left nopadding centered">
							<img src="assets/img/testimonios/1.jpg" alt="">
							<div class="col-xs-12">
								<img src="assets/img/testimonios/1.jpg" alt="">
								<div class="col-xs-12 nopadding heitheen">
									<div class="vertical">
										<div class="col-xs-12">
											<span class="col-xs-12 textWhite">Sistema practico y adaptable, pero más aun,excelente servicio de la empresa que lo desarrolla.</span>
										</div>
									</div>
								</div>
								<div class="col-xs-12">
									<span class="textWhite pull-left">IAN MORAN</span>
									<a class="textWhite pull-right" href="#">INNOVALED</a>
								</div>
							</div>
						</div>
					</div>
					<div class="col-xs-12 col-md-6 text-center nopadding item">
						<div class="col-xs-12 text-left nopadding centered">
							<img src="assets/img/testimonios/2.jpg" alt="">
							<div class="col-xs-12">
								<img src="assets/img/testimonios/2.jpg" alt="">
								<div class="col-xs-12 nopadding heitheen">
									<div class="vertical">
										<div class="col-xs-12">
											<span class="col-xs-12 textWhite">Sistema practico y adaptable, pero más aun,excelente servicio de la empresa que lo desarrolla.</span>
										</div>
									</div>
								</div>
								<div class="col-xs-12">
									<span class="textWhite pull-left">IAN MORAN</span>
									<a class="textWhite pull-right" href="#">INNOVALED</a>
								</div>
							</div>
						</div>
					</div>
					<div class="col-xs-12 col-md-6 text-center nopadding item">
						<div class="col-xs-12 text-left nopadding centered">
							<img src="assets/img/testimonios/3.jpg" alt="">
							<div class="col-xs-12">
								<img src="assets/img/testimonios/3.jpg" alt="">
								<div class="col-xs-12 nopadding heitheen">
									<div class="vertical">
										<div class="col-xs-12">
											<span class="col-xs-12 textWhite">Sistema practico y adaptable, pero más aun,excelente servicio de la empresa que lo desarrolla.</span>
										</div>
									</div>
								</div>
								<div class="col-xs-12">
									<span class="textWhite pull-left">IAN MORAN</span>
									<a class="textWhite pull-right" href="#">INNOVALED</a>
								</div>
							</div>
						</div>
					</div>
					<div class="col-xs-12 col-md-6 text-center nopadding item">
						<div class="col-xs-12 text-left nopadding centered">
							<img src="assets/img/testimonios/4.jpg" alt="">
							<div class="col-xs-12">
								<img src="assets/img/testimonios/4.jpg" alt="">
								<div class="col-xs-12 nopadding heitheen">
									<div class="vertical">
										<div class="col-xs-12">
											<span class="col-xs-12 textWhite">Sistema practico y adaptable, pero más aun,excelente servicio de la empresa que lo desarrolla.</span>
										</div>
									</div>
								</div>
								<div class="col-xs-12">
									<span class="textWhite pull-left">IAN MORAN</span>
									<a class="textWhite pull-right" href="#">INNOVALED</a>
								</div>
							</div>
						</div>
					</div>
					<div class="col-xs-12 col-md-6 text-center nopadding item">
						<div class="col-xs-12 text-left nopadding centered">
							<img src="assets/img/testimonios/5.jpg" alt="">
							<div class="col-xs-12">
								<img src="assets/img/testimonios/5.jpg" alt="">
								<div class="col-xs-12 nopadding heitheen">
									<div class="vertical">
										<div class="col-xs-12">
											<span class="col-xs-12 textWhite">Sistema practico y adaptable, pero más aun,excelente servicio de la empresa que lo desarrolla.</span>
										</div>
									</div>
								</div>
								<div class="col-xs-12">
									<span class="textWhite pull-left">IAN MORAN</span>
									<a class="textWhite pull-right" href="#">INNOVALED</a>
								</div>
							</div>
						</div>
					</div>
					<div class="col-xs-12 col-md-6 text-center nopadding item">
						<div class="col-xs-12 text-left nopadding centered">
							<img src="assets/img/testimonios/6.jpg" alt="">
							<div class="col-xs-12">
								<img src="assets/img/testimonios/6.jpg" alt="">
								<div class="col-xs-12 nopadding heitheen">
									<div class="vertical">
										<div class="col-xs-12">
											<span class="col-xs-12 textWhite">Sistema practico y adaptable, pero más aun,excelente servicio de la empresa que lo desarrolla.</span>
										</div>
									</div>
								</div>
								<div class="col-xs-12">
									<span class="textWhite pull-left">IAN MORAN</span>
									<a class="textWhite pull-right" href="#">INNOVALED</a>
								</div>
							</div>
						</div>
					</div>
					<div class="col-xs-12 col-md-6 text-center nopadding item">
						<div class="col-xs-12 text-left nopadding centered">
							<img src="assets/img/testimonios/7.jpg" alt="">
							<div class="col-xs-12">
								<img src="assets/img/testimonios/7.jpg" alt="">
								<div class="col-xs-12 nopadding heitheen">
									<div class="vertical">
										<div class="col-xs-12">
											<span class="col-xs-12 textWhite">Sistema practico y adaptable, pero más aun,excelente servicio de la empresa que lo desarrolla.</span>
										</div>
									</div>
								</div>
								<div class="col-xs-12">
									<span class="textWhite pull-left">IAN MORAN</span>
									<a class="textWhite pull-right" href="#">INNOVALED</a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<section id="testimonios-clientes" class="backBlue nopaddingBottom">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 nopadding">
				<h2 class="col-xs-12 noHorizontalPadding vxpadding nopaddingTop nomargin">Lo que dicen nuestros clientes</h2>
				<div class="col-xs-12 nopadding" id="slide_logos">

					<div class="col-xs-12 item_logo">
						<div class="col-xs-12 img">
							<div>
								<img src="assets/img/clientes/logo0.png" alt="">
							</div>
						</div>
						<div class="col-xs-12 info">
							<h5>MHUSA<small>Accesorios y bisutería</small></h5>
						</div>
					</div>

					<div class="col-xs-12 item_logo">
						<div class="col-xs-12 img">
							<div>
								<img src="assets/img/clientes/logo1.png" alt="">
							</div>
						</div>
						<div class="col-xs-12 info">
							<h5>LEVELSTORE<small>Tienda on line</small></h5>
						</div>
					</div>

					<div class="col-xs-12 item_logo">
						<div class="col-xs-12 img">
							<div>
								<img src="assets/img/clientes/logo2.png" alt="">
							</div>
						</div>
						<div class="col-xs-12 info">
							<h5>STYLE & DESIGN<small>Diseño de interiores</small></h5>
						</div>
					</div>

					<div class="col-xs-12 item_logo">
						<div class="col-xs-12 img">
							<div>
								<img src="assets/img/clientes/logo3.png" alt="">
							</div>
						</div>
						<div class="col-xs-12 info">
							<h5>JCV THE BEST<small>Ferretería</small></h5>
						</div>
					</div>

					<div class="col-xs-12 item_logo">
						<div class="col-xs-12 img">
							<div>
								<img src="assets/img/clientes/logo4.png" alt="">
							</div>
						</div>
						<div class="col-xs-12 info">
							<h5>INVERSIONES GLORIA<small>Transporte terrestre</small></h5>
						</div>
					</div>

					<div class="col-xs-12 item_logo">
						<div class="col-xs-12 img">
							<div>
								<img src="assets/img/clientes/logo5.png" alt="">
							</div>
						</div>
						<div class="col-xs-12 info">
							<h5>FITO MADERERA<small>Carpintería</small></h5>
						</div>
					</div>

				</div>
			</div>
		</div>
	</div>
</section>



<section id="clientes" class="backBlue nopaddingBottom">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 nopadding">
				<h2 class="col-xs-12 noHorizontalPadding vxpadding nopaddingTop nomargin">Nuestro clientes</h2>
				<div class="col-xs-12 noHorizontalPadding">
					<div class="col-xs-3 col-md-2 text-center nopadding item">
						<div class="col-xs-12 noHorizontalPadding centered">
							<img src="assets/img/clientes/1.svg" alt="" class="centered vpadding">
							<h5 class="col-xs-12 noHorizontalPadding bold text-center centered">New Tech Electro</h5>
							<span class="col-xs-12 noHorizontalPadding text-center centered">New Tech Electro S.A.C.</span>
						</div>
					</div>
					<div class="col-xs-3 col-md-2 text-center nopadding item">
						<div class="col-xs-12 noHorizontalPadding centered">
							<img src="assets/img/clientes/2.svg" alt="" class="centered vpadding">
							<h5 class="col-xs-12 noHorizontalPadding bold text-center centered">Level Store</h5>
							<span class="col-xs-12 noHorizontalPadding text-center centered">Level Store S.A.C.</span>
						</div>
					</div>
					<div class="col-xs-3 col-md-2 text-center nopadding item">
						<div class="col-xs-12 noHorizontalPadding centered">
							<img src="assets/img/clientes/3.svg" alt="" class="centered vpadding">
							<h5 class="col-xs-12 noHorizontalPadding bold text-center centered">Style & Design</h5>
							<span class="col-xs-12 noHorizontalPadding text-center centered">Style & Design S.A.C.</span>
						</div>
					</div>
					<div class="col-xs-3 col-md-2 text-center nopadding item">
						<div class="col-xs-12 noHorizontalPadding centered">
							<img src="assets/img/clientes/4.svg" alt="" class="centered vpadding">
							<h5 class="col-xs-12 noHorizontalPadding bold text-center centered">JCV The best</h5>
							<span class="col-xs-12 noHorizontalPadding text-center centered">JCV The best S.A.C.</span>
						</div>
					</div>
					<div class="col-xs-3 col-md-2 text-center nopadding item">
						<div class="col-xs-12 noHorizontalPadding centered">
							<img src="assets/img/clientes/5.svg" alt="" class="centered vpadding">
							<h5 class="col-xs-12 noHorizontalPadding bold text-center centered">Inversiones Gloria</h5>
							<span class="col-xs-12 noHorizontalPadding text-center centered">Inversiones Gloria E.I.R.L</span>
						</div>
					</div>
					<div class="col-xs-3 col-md-2 text-center nopadding item">
						<div class="col-xs-12 noHorizontalPadding centered">
							<img src="assets/img/clientes/6.svg" alt="" class="centered vpadding">
							<h5 class="col-xs-12 noHorizontalPadding bold text-center centered">Fito maderera</h5>
							<span class="col-xs-12 noHorizontalPadding text-center centered">Madera</span>
						</div>
					</div>

					<div class="col-xs-12 noHorizontalPadding vxpadding text-center">
						<a href="prueba" class="btn2 centered">PRUEBA GRATIS</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<section id="precios" class="backBlue">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 nopadding">
				<h2 class="col-xs-12 noHorizontalPadding vxpadding nopaddingTop nomargin">Precios SIGA</h2>
				<div class="col-xs-12 noHorizontalPadding text-center">
					<p class="col-xs-12 nopadding text-center nomargin">Nuestro servicio incluye soporte y capacitación permanente, no tenemos precios ocultos</p>
					<p class="col-xs-12 col-sm-8 vpadding noHorizontalPadding centered">Elige el plan que mejor se acomode a tu negocio. Puedes simular y personalizar según el número de sucursales que necesites</p>
				</div>
			</div>
			<div class="col-xs-12 nopadding">

				<div class="col-xs-12 col-sm-6 col-md-3 nopadding item text-center">
					<div class="col-xs-12 centered">
						<div class="col-xs-12 nopadding">
							<div class="col-xs-12 nopadding vpadding text-center">
								<img src="assets/img/icons/price1.svg" alt="" class="col-xs-12 nopadding centered">
							</div>
							<h3 class="col-xs-12 noHorizontalPadding vpadding nomargin nopaddingTop">FREE</h3>
							<h3 class="col-xs-12 nopadding nomargin bold">$ 0 / <small>Anual</small></h3>
							<ul>
								<li>Punto de venta</li>
								<li>Compras y gastos</li>
								<li>Control de inventario</li>
								<li>Caja y bancos</li>
								<li>Proveedores ( cuentas por pagar )</li>
								<li>Clientes ( cuentas por cobrar )</li>
								<li>Informes en linea</li>
								<li>App de ventas</li>
								<li>Certificado SSL</li>
							</ul>
							<div class="col-xs-12 noHorizontalPadding vpadding text-center">
								<button class="centered">PRUEBA GRATIS</button>
							</div>
						</div>
						<div class="col-xs-12 noHorizontalPadding vpadding text-left">
  							<div class="form-group">
  							  	<label for="exampleInputEmail1"># Sucursales</label>
  							  	<select class="form-control" name="" id="">
  							  		<option value="1 Sucursal">1 Sucursal</option>
  							  	</select>
  							</div>
  							<div class="form-group">
  							  	<label for="exampleInputEmail1"># Usuarios</label>
  							  	<select class="form-control" name="" id="">
  							  		<option value="3  Usuarios">3  Usuarios</option>
  							  	</select>
  							</div>
  							<div class="form-group">
  							  	<label for="exampleInputEmail1"># Productos</label>
  							  	<select class="form-control" name="" id="">
  							  		<option value="100 Productos">100 Productos</option>
  							  	</select>
  							</div>
  							<div class="form-group">
  							  	<label for="exampleInputEmail1">Dominio propio</label>
  							  	<select class="form-control" name="" id="">
  							  		<option value="Si">Si</option>
  							  	</select>
  							</div>
  							<div class="form-group">
  							  	<label for="exampleInputEmail1">Facturación electronica</label>
  							  	<select class="form-control" name="" id="">
  							  		<option value="Si">Si</option>
  							  	</select>
  							</div>
  							<h3 class="col-xs-12 noHorizontalPadding vpadding nomargin bold text-center">$ 0 / <small>Anual</small></h3>
  							<div class="col-xs-12 noHorizontalPadding vpadding text-center">
								<button class="centered">CONTRATAR</button>
							</div>
						</div>
					</div>
				</div>

				<div class="col-xs-12 col-sm-6 col-md-3 nopadding item text-center">
					<div class="col-xs-12 centered">
						<div class="col-xs-12 nopadding">
							<div class="col-xs-12 nopadding vpadding text-center">
								<img src="assets/img/icons/price2.svg" alt="" class="col-xs-12 nopadding centered">
							</div>
							<h3 class="col-xs-12 noHorizontalPadding vpadding nomargin nopaddingTop">BASICO</h3>
							<h3 class="col-xs-12 nopadding nomargin bold">$ 350.00 / <small>Anual</small></h3>
							<ul>
								<li>Punto de venta</li>
								<li>Compras y gastos</li>
								<li>Control de inventario</li>
								<li>Caja y bancos</li>
								<li>Proveedores ( cuentas por pagar )</li>
								<li>Clientes ( cuentas por cobrar )</li>
								<li>Informes en linea</li>
								<li>App de ventas</li>
								<li>Certificado SSL</li>
							</ul>
							<div class="col-xs-12 noHorizontalPadding vpadding text-center">
								<button class="centered">PRUEBA GRATIS</button>
							</div>
						</div>
						<div class="col-xs-12 noHorizontalPadding vpadding text-left">
  							<div class="form-group">
  							  	<label for="exampleInputEmail1"># Sucursales</label>
  							  	<select class="form-control" name="" id="">
  							  		<option value="1 Sucursal">1 Sucursal</option>
  							  	</select>
  							</div>
  							<div class="form-group">
  							  	<label for="exampleInputEmail1"># Usuarios</label>
  							  	<select class="form-control" name="" id="">
  							  		<option value="3  Usuarios">3  Usuarios</option>
  							  	</select>
  							</div>
  							<div class="form-group">
  							  	<label for="exampleInputEmail1"># Productos</label>
  							  	<select class="form-control" name="" id="">
  							  		<option value="100 Productos">100 Productos</option>
  							  	</select>
  							</div>
  							<div class="form-group">
  							  	<label for="exampleInputEmail1">Dominio propio</label>
  							  	<select class="form-control" name="" id="">
  							  		<option value="Si">Si</option>
  							  	</select>
  							</div>
  							<div class="form-group">
  							  	<label for="exampleInputEmail1">Facturación electronica</label>
  							  	<select class="form-control" name="" id="">
  							  		<option value="Si">Si</option>
  							  	</select>
  							</div>
  							<h3 class="col-xs-12 noHorizontalPadding vpadding nomargin bold text-center">$ 350.00 / <small>Anual</small></h3>
  							<div class="col-xs-12 noHorizontalPadding vpadding text-center">
								<button class="centered">CONTRATAR</button>
							</div>
						</div>
					</div>
				</div>

				<div class="col-xs-12 col-sm-6 col-md-3 nopadding item text-center">
					<div class="col-xs-12 centered">
						<div class="col-xs-12 nopadding">
							<div class="col-xs-12 nopadding vpadding text-center">
								<img src="assets/img/icons/price3.svg" alt="" class="col-xs-12 nopadding centered">
							</div>
							<h3 class="col-xs-12 noHorizontalPadding vpadding nomargin nopaddingTop">ESTANDAR</h3>
							<h3 class="col-xs-12 nopadding nomargin bold">$ 550.00 / <small>Anual</small></h3>
							<ul>
								<li>Punto de venta</li>
								<li>Compras y gastos</li>
								<li>Control de inventario</li>
								<li>Caja y bancos</li>
								<li>Proveedores ( cuentas por pagar )</li>
								<li>Clientes ( cuentas por cobrar )</li>
								<li>Informes en linea</li>
								<li>App de ventas</li>
								<li>Certificado SSL</li>
							</ul>
							<div class="col-xs-12 noHorizontalPadding vpadding text-center">
								<button class="centered">PRUEBA GRATIS</button>
							</div>
						</div>
						<div class="col-xs-12 noHorizontalPadding vpadding text-left">
  							<div class="form-group">
  							  	<label for="exampleInputEmail1"># Sucursales</label>
  							  	<select class="form-control" name="" id="">
  							  		<option value="1 Sucursal">1 Sucursal</option>
  							  	</select>
  							</div>
  							<div class="form-group">
  							  	<label for="exampleInputEmail1"># Usuarios</label>
  							  	<select class="form-control" name="" id="">
  							  		<option value="3  Usuarios">3  Usuarios</option>
  							  	</select>
  							</div>
  							<div class="form-group">
  							  	<label for="exampleInputEmail1"># Productos</label>
  							  	<select class="form-control" name="" id="">
  							  		<option value="100 Productos">100 Productos</option>
  							  	</select>
  							</div>
  							<div class="form-group">
  							  	<label for="exampleInputEmail1">Dominio propio</label>
  							  	<select class="form-control" name="" id="">
  							  		<option value="Si">Si</option>
  							  	</select>
  							</div>
  							<div class="form-group">
  							  	<label for="exampleInputEmail1">Facturación electronica</label>
  							  	<select class="form-control" name="" id="">
  							  		<option value="Si">Si</option>
  							  	</select>
  							</div>
  							<h3 class="col-xs-12 noHorizontalPadding vpadding nomargin bold text-center">$ 550.00 / <small>Anual</small></h3>
  							<div class="col-xs-12 noHorizontalPadding vpadding text-center">
								<button class="centered">CONTRATAR</button>
							</div>
						</div>
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 col-md-3 nopadding item text-center">
					<div class="col-xs-12 centered">
						<div class="col-xs-12 nopadding">
							<div class="col-xs-12 nopadding vpadding text-center">
								<img src="assets/img/icons/price4.svg" alt="" class="col-xs-12 nopadding centered">
							</div>
							<h3 class="col-xs-12 noHorizontalPadding vpadding nomargin nopaddingTop">FULL</h3>
							<h3 class="col-xs-12 nopadding nomargin bold">$ 1500.00 / <small>Anual</small></h3>
							<ul>
								<li>Punto de venta</li>
								<li>Compras y gastos</li>
								<li>Control de inventario</li>
								<li>Caja y bancos</li>
								<li>Proveedores ( cuentas por pagar )</li>
								<li>Clientes ( cuentas por cobrar )</li>
								<li>Informes en linea</li>
								<li>App de ventas</li>
								<li>Certificado SSL</li>
							</ul>
							<div class="col-xs-12 noHorizontalPadding vpadding text-center">
								<button class="centered">PRUEBA GRATIS</button>
							</div>
						</div>
						<div class="col-xs-12 noHorizontalPadding vpadding text-left">
  							<div class="form-group">
  							  	<label for="exampleInputEmail1"># Sucursales</label>
  							  	<select class="form-control" name="" id="">
  							  		<option value="1 Sucursal">1 Sucursal</option>
  							  	</select>
  							</div>
  							<div class="form-group">
  							  	<label for="exampleInputEmail1"># Usuarios</label>
  							  	<select class="form-control" name="" id="">
  							  		<option value="3  Usuarios">3  Usuarios</option>
  							  	</select>
  							</div>
  							<div class="form-group">
  							  	<label for="exampleInputEmail1"># Productos</label>
  							  	<select class="form-control" name="" id="">
  							  		<option value="100 Productos">100 Productos</option>
  							  	</select>
  							</div>
  							<div class="form-group">
  							  	<label for="exampleInputEmail1">Dominio propio</label>
  							  	<select class="form-control" name="" id="">
  							  		<option value="Si">Si</option>
  							  	</select>
  							</div>
  							<div class="form-group">
  							  	<label for="exampleInputEmail1">Facturación electronica</label>
  							  	<select class="form-control" name="" id="">
  							  		<option value="Si">Si</option>
  							  	</select>
  							</div>
  							<h3 class="col-xs-12 noHorizontalPadding vpadding nomargin bold text-center">$ 1500.00 / <small>Anual</small></h3>
  							<div class="col-xs-12 noHorizontalPadding vpadding text-center">
								<button class="centered">CONTRATAR</button>
							</div>
						</div>
					</div>
				</div>

			</div>
		</div>
	</div>
</section>
<section id="infoContacto">
	<img src="assets/img/infoContacto.svg" alt="" class="backed">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 text-center">
				<div class="col-xs-12 noHorizontalPadding heitheen">
					<h2 class="col-xs-12 nopadding">CONTACTENOS</h2>
				</div>
				<div class="col-xs-12 noHorizontalPadding text-center">
					<div class="figure col-xs-12 noHorizontalPadding centered">
						<a href="" target="_blank" class="skype">
							<img src="assets/img/icons/skype_1.svg" alt="">
						</a>
						<a href="https://api.whatsapp.com/send?phone=513939907" target="_blank">
							<img src="assets/img/icons/wp_1.svg" alt="">
						</a>
						<a href="mailto:ventas@siga.com.pe">
							<img src="assets/img/icons/email_1.svg" alt="">
						</a>
					</div>
				</div>
				<div class="col-xs-12 noHorizontalPadding heitheen">
					<h4 class="col-xs-12 noHorizontalPadding nomargin nopaddingTop">Llamenos ahora</h4>
					<h3 class="col-xs-12 nopadding"><a href="tel:+513939907">+51 39 39 907</a></h3>
				</div>
			</div>
		</div>
	</div>
</section>
-->


<!-- Modal -->
<div class="modal fade modal_stetic" id="modalVideo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><img src="assets/img/closemodal.svg"></button>
			<div class="modal-body">
				<div class="row">
					<div class="col-xs-12 noHorizontalPadding vpadding nopaddingTop text-center">
						<img src="assets/img/logo_svg.svg" alt="" class="col-xs-12 noHorizontalPadding logo_modal centered">
					</div>
					<div class="col-xs-12 nopadding text-center" id="video">
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="SkypeButton_Call_yinblack_1">
 <script type="text/javascript">
 Skype.ui({
 "name": "call",
 "element": "SkypeButton_Call_yinblack_1",
 "participants": ["yinblack"]
 });
 </script>
</div>
