<section id="empresa_size" class="startSection">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 nopadding">
				<h2 class="col-xs-12 noHorizontalPadding vxpadding nopaddingTop nomargin textBlue">¿Tienes el control total de tu empresa?</h2>
				<div class="col-xs-12 noHorizontalPadding vpadding nopaddingBottom modalidades">
          <div class="col-xs-12 col-sm-6 text-center">
            <p class="col-xs-12 noHorizontalPadding textGrey">SIGA es la solución que necesitas para fortalecer el crecimiento de tu compañía y hacer tus procesos más fáciles y rápidos. Tu información siempre estará segura con certificado SSL y disponible desde la nube. Puedes acceder a tus datos desde tu oficina o desde la China.</p>
            <h4 class="col-xs-12 noHorizontalPadding vxxpadding nopaddingBottom nomargin textBlue text-center">Contrata el paquete SIGA ESTÁNDAR para mantener tus operaciones integradas y automatizadas</h4>
          </div>
          <div class="col-xs-12 col-sm-6 text-center nopadding icons">
              <div class="col-xs-12 noHorizontalPadding centered">

                <div class="col-xs-6 col-sm-4 col-md-2 noHorizontalPadding text-center item">
                  <div class="col-xs-12 noHorizontalPadding centered">
                    <img class="col-xs-12 nopadding" src="assets/img/icons/empresa_peq/ventas.svg" alt="">
                  </div>
                  <p class="col-xs-12 noHorizontalPadding text-center textGrey2">Ventas</p>
                </div>
                <div class="col-xs-6 col-sm-4 col-md-2 noHorizontalPadding text-center item">
                  <div class="col-xs-12 noHorizontalPadding centered">
                    <img class="col-xs-12 nopadding" src="assets/img/icons/empresa_peq/ofertas.svg" alt="">
                  </div>
                  <p class="col-xs-12 noHorizontalPadding text-center textGrey2">Ofertas</p>
                </div>
                <div class="col-xs-6 col-sm-4 col-md-2 noHorizontalPadding text-center item">
                  <div class="col-xs-12 noHorizontalPadding centered">
                    <img class="col-xs-12 nopadding" src="assets/img/icons/empresa_peq/aplicativo.svg" alt="">
                  </div>
                  <p class="col-xs-12 noHorizontalPadding text-center textGrey2">Aplicativo Móvil</p>
                </div>
                <div class="col-xs-6 col-sm-4 col-md-2 noHorizontalPadding text-center item">
                  <div class="col-xs-12 noHorizontalPadding centered">
                    <img class="col-xs-12 nopadding" src="assets/img/icons/empresa_peq/facturacion.svg" alt="">
                  </div>
                  <p class="col-xs-12 noHorizontalPadding text-center textGrey2">Facturación Electronica</p>
                </div>
								<div class="col-xs-6 col-sm-4 col-md-2 noHorizontalPadding text-center item">
                  <div class="col-xs-12 noHorizontalPadding centered">
                    <img class="col-xs-12 nopadding" src="assets/img/icons/empresa_peq/clientes.svg" alt="">
                  </div>
                  <p class="col-xs-12 noHorizontalPadding text-center textGrey2">Clientes</p>
                </div>
								<div class="col-xs-6 col-sm-4 col-md-2 noHorizontalPadding text-center item">
                  <div class="col-xs-12 noHorizontalPadding centered">
                    <img class="col-xs-12 nopadding" src="assets/img/icons/empresa_peq/inventario.svg" alt="">
                  </div>
                  <p class="col-xs-12 noHorizontalPadding text-center textGrey2">Inventario</p>
                </div>
								<div class="col-xs-6 col-sm-4 col-md-2 noHorizontalPadding text-center item">
                  <div class="col-xs-12 noHorizontalPadding centered">
                    <img class="col-xs-12 nopadding" src="assets/img/icons/empresa_peq/almacen.svg" alt="">
                  </div>
                  <p class="col-xs-12 noHorizontalPadding text-center textGrey2">Almacen</p>
                </div>
								<div class="col-xs-6 col-sm-4 col-md-2 noHorizontalPadding text-center item">
                  <div class="col-xs-12 noHorizontalPadding centered">
                    <img class="col-xs-12 nopadding" src="assets/img/icons/empresa_peq/sucursal.svg" alt="">
                  </div>
                  <p class="col-xs-12 noHorizontalPadding text-center textGrey2">Sucursal</p>
                </div>
								<div class="col-xs-6 col-sm-4 col-md-2 noHorizontalPadding text-center item">
                  <div class="col-xs-12 noHorizontalPadding centered">
                    <img class="col-xs-12 nopadding" src="assets/img/icons/empresa_peq/kardex.svg" alt="">
                  </div>
                  <p class="col-xs-12 noHorizontalPadding text-center textGrey2">Kardex</p>
                </div>
                <div class="col-xs-6 col-sm-4 col-md-2 noHorizontalPadding text-center item">
                  <div class="col-xs-12 noHorizontalPadding centered">
                    <img class="col-xs-12 nopadding" src="assets/img/icons/empresa_peq/reportes.svg" alt="">
                  </div>
                  <p class="col-xs-12 noHorizontalPadding text-center textGrey2">Reportes</p>
                </div>
                <div class="col-xs-6 col-sm-4 col-md-2 noHorizontalPadding text-center item">
                  <div class="col-xs-12 noHorizontalPadding centered">
                    <img class="col-xs-12 nopadding" src="assets/img/icons/empresa_peq/caja.svg" alt="">
                  </div>
                  <p class="col-xs-12 noHorizontalPadding text-center textGrey2">Caja</p>
                </div>
                <div class="col-xs-6 col-sm-4 col-md-2 noHorizontalPadding text-center item">
                  <div class="col-xs-12 noHorizontalPadding centered">
                    <img class="col-xs-12 nopadding" src="assets/img/icons/empresa_peq/soporte.svg" alt="">
                  </div>
                  <p class="col-xs-12 noHorizontalPadding text-center textGrey2">Soporte</p>
                </div>
                <div class="col-xs-6 col-sm-4 col-md-2 noHorizontalPadding text-center item">
                  <div class="col-xs-12 noHorizontalPadding centered">
                    <img class="col-xs-12 nopadding" src="assets/img/icons/empresa_peq/usuarios.svg" alt="">
                  </div>
                  <p class="col-xs-12 noHorizontalPadding text-center textGrey2">Usuarios</p>
                </div>

              </div>
          </div>
				</div>
				<div class="col-xs-12 noHorizontalPadding text-center">
					<div class="col-xs-12 centered container_form">
						<h3 class="col-xs-12 vxpadding nopaddingTop nomarginTop textBlue text-left">Llena este formulario y comienza hoy</h3>
						<div class="col-xs-12 shadow">
							<form class="col-xs-12" id="form_peq_empresa">
								<input type="hidden" name="captcha" value="">
								<div class="col-xs-12 col-sm-6 noHorizontalPadding vpadding nopaddingTop text-center">
									<div class="col-xs-12 form-group centered item_input">
                  	<div class="inputContent input-effect">
                    	<input class="effect-16" type="text" id="nombres" name="nombres">
                    	<label>Nombres</label>
                    	<span class="focus-border"></span>
                  	</div>
									</div>
                </div>

								<div class="col-xs-12 col-sm-6 noHorizontalPadding vpadding nopaddingTop text-center">
									<div class="col-xs-12 form-group centered item_input">
                  	<div class="inputContent input-effect">
                    	<input class="effect-16" type="text" id="apellidos" name="apellidos">
                    	<label>Apellidos</label>
                    	<span class="focus-border"></span>
                  	</div>
									</div>
                </div>

								<div class="col-xs-12 col-sm-6 noHorizontalPadding vpadding nopaddingTop text-center">
									<div class="col-xs-12 form-group centered item_input">
                  	<div class="inputContent input-effect">
                    	<input class="effect-16" type="text" id="correo" name="correo">
                    	<label>Correo Electrónico</label>
                    	<span class="focus-border"></span>
                  	</div>
									</div>
                </div>

								<div class="col-xs-12 col-sm-6 noHorizontalPadding vpadding nopaddingTop text-center">
									<div class="col-xs-12 form-group centered item_input">
                  	<div class="inputContent input-effect">
                    	<input class="effect-16" type="text" id="telefono" name="telefono">
                    	<label>Teléfono</label>
                    	<span class="focus-border"></span>
                  	</div>
									</div>
                </div>

								<div class="col-xs-12 col-sm-6 noHorizontalPadding vpadding nopaddingTop text-center">
									<div class="col-xs-12 form-group centered item_input">
                  	<div class="inputContent input-effect">
                    	<input class="effect-16" type="text" id="empresa" name="empresa">
                    	<label>Nombre de tu empresa</label>
                    	<span class="focus-border"></span>
                  	</div>
									</div>
                </div>

								<div class="col-xs-12 col-sm-6 noHorizontalPadding vpadding nopaddingTop text-center">
									<div class="col-xs-12 form-group centered item_input">
                  	<div class="inputContent input-effect">
											<select class="effect-16" id="almacenes" name="almacenes">
												<option value="" selected hidden></option>
												<option value="#">Valor 1</option>
												<option value="#">Valor 2</option>
												<option value="#">Valor 3</option>
											</select>
                    	<label>Alamacenes y sucursales</label>
                    	<span class="focus-border"></span>
                  	</div>
									</div>
                </div>

								<div class="col-xs-12 noHorizontalPadding vpadding nopaddingTop text-center">
									<div class="col-xs-12 form-group centered item_input_area">
                  	<div class="inputContent input-effect">
											<textarea class="effect-16" name="comentarios" id="comentarios" rows="4" cols="80"></textarea>
                    	<label>Comentarios</label>
                    	<span class="focus-border"></span>
                  	</div>
									</div>
                </div>

								<div class="col-xs-12 noHorizontalPadding vpadding nopaddingTop text-center">
									<a href="#" class="btn2 centered" id="send_contacto_empresa">QUIERO MI DEMO EXCLUSIVO GRATIS</a>
								</div>

							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
