<section id="tabla_planes" class="startSection">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 nopadding">
        <div class="col-xs-12 text-center">
          <h3 class="col-xs-12 noHorizontalPadding vxpadding nopaddingTop nomargin bold">Nuestro servicio incluye soporte y capacitación permanente, no tenemos precios ocultos. <br>Elige el plan que mejor se acomode a tu negocio.</h3>
        </div>
        <div class="col-xs-12 planes_">
            <div class="col-xs-12 header_table">
              <div class="col-xs-12 noHorizontalPadding">
                <h1>PLANES TARIFARIOS</h1>
                <div>
                  <h4 class="green">SIGA Expert</h4>
                  <span>IMPLEMENTACIÓN<strong>$3000</strong></span>
                </div>
                <div>
                  <h4 class="grey">SIGA Estandar</h4>
                  <span>IMPLEMENTACIÓN<strong>$2000</strong></span>
                </div>
                <div>
                  <h4 class="grey">SIGA Basic</h4>
                  <span>IMPLEMENTACIÓN<strong>$1000</strong></span>
                </div>
              </div>
            </div>
            <ul class="col-xs-12">
              <div class="title orange">
                <div class="vertical">
                  <h4 class="col-xs-12 text-center textWhite">VENTAS</h4>
                </div>
              </div>
              <li><span class="info">Tienda Online E-commerce</span><span class="ok"></span><span class="x"></span><span class="x"></span></li>
              <li><span class="info">Convertir Cotizaciones a Ventas</span><span class="ok"></span><span class="ok"></span><span class="x"></span></li>
              <li><span class="info">Promociones de Ofertas</span><span class="ok"></span><span class="ok"></span><span class="x"></span></li>
              <li><span class="info">Ventas a Credito</span><span class="ok"></span><span class="ok"></span><span class="ok"></span></li>
              <li><span class="info">Cronograma de Cobranzas</span><span class="ok"></span><span class="ok"></span><span class="ok"></span></li>
              <li><span class="info">Traspaso Automatizado</span><span class="ok"></span><span class="ok"></span><span class="ok"></span></li>
            </ul>
            <ul class="col-xs-12">
              <div class="title bluesky">
                <div class="vertical">
                  <h4 class="col-xs-12 text-center textWhite">APLICATIVO MOVIL</h4>
                </div>
              </div>
              <li><span class="info">Registro de Ventas</span><span class="ok"></span><span class="ok"></span><span class="ok"></span></li>
              <li><span class="info">Registro de Clientes</span><span class="ok"></span><span class="ok"></span><span class="ok"></span></li>
              <li><span class="info">Ventas Totales del Día por Vendedor</span><span class="ok"></span><span class="ok"></span><span class="ok"></span></li>
            </ul>
            <ul class="col-xs-12">
              <div class="title blueobs">
                <div class="vertical">
                  <h4 class="col-xs-12 text-center textWhite">DOCUMENTOS</h4>
                </div>
              </div>
              <li><span class="info">Facturación y boleta Electrónica</span><span class="ok"></span><span class="ok"></span><span class="ok"></span></li>
              <li><span class="info">Guía de Remisión Electrónica</span><span class="ok"></span><span class="ok"></span><span class="ok"></span></li>
              <li><span class="info">Notas de Débito y Crédito</span><span class="ok"></span><span class="ok"></span><span class="ok"></span></li>
            </ul>
            <ul class="col-xs-12">
              <div class="title green">
                <div class="vertical">
                  <h4 class="col-xs-12 text-center textWhite">CLIENTES</h4>
                </div>
              </div>
              <li><span class="info">Envío de Facturación por Correo</span><span class="ok"></span><span class="ok"></span><span class="ok"></span></li>
              <li><span class="info">Cuentas por Cobrar</span><span class="ok"></span><span class="ok"></span><span class="ok"></span></li>
              <li><span class="info">Estado de Cuenta de Clientes</span><span class="ok"></span><span class="ok"></span><span class="ok"></span></li>
              <li><span class="info">Calendario de Cobranzas</span><span class="ok"></span><span class="ok"></span><span class="ok"></span></li>
            </ul>
            <ul class="col-xs-12">
              <div class="title purple">
                <div class="vertical">
                  <h4 class="col-xs-12 text-center textWhite">INVENTARIO</h4>
                </div>
              </div>
              <li><span class="info">Traspasos de Almacén</span><span class="ok"></span><span class="ok"></span><span class="ok"></span></li>
              <li><span class="info">Control de Inventario</span><span class="ok"></span><span class="ok"></span><span class="ok"></span></li>
              <li><span class="info">Kardex valorizado</span><span class="ok"></span><span class="ok"></span><span class="x"></span></li>
              <li><span class="info">Kardex Permanente</span><span class="ok"></span><span class="ok"></span><span class="x"></span></li>
            </ul>
            <ul class="col-xs-12">
              <div class="title red">
                <div class="vertical">
                  <h4 class="col-xs-12 text-center textWhite">LOCALES</h4>
                </div>
              </div>
              <li><span class="info">Sucursales</span><span class="numb">2</span><span class="numb">1</span><span class="x"></span></li>
              <li><span class="info">Almacenes</span><span class="numb">6</span><span class="numb">4</span><span class="numb">1</span></li>
            </ul>
            <ul class="col-xs-12">
              <div class="title brown">
                <div class="vertical">
                  <h4 class="col-xs-12 text-center textWhite">CAJA</h4>
                </div>
              </div>
              <li><span class="info">Registro de Gastos</span><span class="ok"></span><span class="ok"></span><span class="ok"></span></li>
              <li><span class="info">Cierre de Caja</span><span class="ok"></span><span class="ok"></span><span class="ok"></span></li>
              <li><span class="info">Cuadre de Caja</span><span class="ok"></span><span class="ok"></span><span class="ok"></span></li>
              <li><span class="info">Control de Movimientos Bancarios</span><span class="ok"></span><span class="ok"></span><span class="x"></span></li>
            </ul>
            <ul class="col-xs-12">
              <div class="title brownlight">
                <div class="vertical">
                  <h4 class="col-xs-12 text-center textWhite">PROVEEDORES</h4>
                </div>
              </div>
              <li><span class="info">Cuentas por Pagar</span><span class="ok"></span><span class="ok"></span><span class="ok"></span></li>
              <li><span class="info">Cronograma de Pagos</span><span class="ok"></span><span class="ok"></span><span class="ok"></span></li>
              <li><span class="info">Calendario de Pagos</span><span class="ok"></span><span class="ok"></span><span class="ok"></span></li>
            </ul>
            <ul class="col-xs-12">
              <div class="title purple">
                <div class="vertical">
                  <h4 class="col-xs-12 text-center textWhite">REPORTES</h4>
                </div>
              </div>
              <li><span class="info">Valorización de Inventario</span><span class="ok"></span><span class="ok"></span><span class="ok"></span></li>
              <li><span class="info">Reporte de Margen de Utilidad</span><span class="ok"></span><span class="ok"></span><span class="ok"></span></li>
              <li><span class="info">Productos Más Vendidos</span><span class="ok"></span><span class="ok"></span><span class="x"></span></li>
              <li><span class="info">Ventas por Vendedor</span><span class="ok"></span><span class="ok"></span><span class="x"></span></li>
              <li><span class="info">Comisión por Vendedor</span><span class="ok"></span><span class="ok"></span><span class="x"></span></li>
              <li><span class="info">Gasto del Día</span><span class="ok"></span><span class="ok"></span><span class="ok"></span></li>
              <li><span class="info">Ventas por Sucursal</span><span class="ok"></span><span class="ok"></span><span class="x"></span></li>
              <li><span class="info">Rotación de Productos</span><span class="ok"></span><span class="ok"></span><span class="x"></span></li>
            </ul>
            <ul class="col-xs-12">
              <div class="title blueobs">
                <div class="vertical">
                  <h4 class="col-xs-12 text-center textWhite">SOPORTE</h4>
                </div>
              </div>
              <li><span class="info">Capacitación (Remota/Presencial)</span><span class="numb">10 hrs</span><span class="numb">6 hrs</span><span class="numb">4 hrs</span></li>
              <li><span class="info">Soporte Presencial</span><span class="numb">Si</span><span class="numb">Si</span><span class="numb">Si</span></li>
              <li><span class="info">Soporte Remoto</span><span class="numb">365 días</span><span class="numb">365 días</span><span class="numb">365 días</span></li>
            </ul>
            <ul class="col-xs-12">
              <div class="title orange">
                <div class="vertical">
                  <h4 class="col-xs-12 text-center textWhite">USUARIOS</h4>
                </div>
              </div>
              <li><span class="info"></span><span class="numb">12</span><span class="numb">8</span><span class="numb">3</span></li>
            </ul>
        </div>
			</div>
		</div>
	</div>
</section>
