<section id="pruebas" class="backBlue startSection">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 nopadding">
				<h2 class="col-xs-12 noHorizontalPadding vxpadding nopaddingTop nomargin">Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</h2>
				<div class="col-xs-12 noHorizontalPadding vpadding text-center">
					<div class="col-xs-12 nopadding centered control_slide_pruebas">
						<a href="#" class="active">
							<div class="col-xs-12 nopadding text-center">
								<svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 500 500" style="enable-background:new 0 0 500 500;" xml:space="preserve">
									<g>
										<path class="st0" d="M157.4,266l318.1-163L211.7,297l155.2,100.9L475.6,103L25,196.1L157.4,266z M157.4,266"/>
										<path class="st1" d="M211.7,297l-30.5,100.9L157.4,266l318.1-163L211.7,297z M211.7,297"/>
										<path class="st1" d="M211.7,297l-31,100.9l91.9-61.3L211.7,297z M211.7,297"/>
									</g>
								</svg>
							</div>
							<h4 class="col-xs-12 noHorizontalPadding vpadding nopaddingTop nomargin">PRUEBA RAPIDA</h4>
						</a>
						<a href="#">
							<div class="col-xs-12 nopadding text-center">
								<svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 500 500" style="enable-background:new 0 0 500 500;" xml:space="preserve">
									<path class="st1" d="M401.7,420.8H98.1c-8.4,0-15.7-5.5-18.2-13.5L7.8,170.1c-2.2-7.2,0.1-15.1,5.8-20c5.7-4.9,13.8-5.9,20.6-2.6l103.8,50.6l97.4-112.3c3.6-4.2,8.8-6.5,14.3-6.5c5.5,0,10.7,2.4,14.3,6.5l97.4,112.3l103.8-50.6c6.8-3.3,14.9-2.3,20.6,2.6c5.7,4.9,8,12.7,5.8,20l-72.1,237.2C417.4,415.3,410.1,420.8,401.7,420.8z M112.2,382.8h275.5L443,200.7l-77.8,37.9c-7.7,3.8-17,1.9-22.6-4.6l-92.6-106.8L157.3,234c-5.6,6.5-14.9,8.4-22.6,4.6l-77.8-37.9L112.2,382.8z"/>
								</svg>
							</div>
							<h4 class="col-xs-12 noHorizontalPadding vpadding nopaddingTop nomargin">PRUEBA EXCLUSIVA</h4>
						</a>
					</div>
				</div>
				<div class="col-xs-12 noHorizontalPadding" id="slider_pruebas">

					<div class="col-xs-12 item">
						<div class="col-xs-12 col-sm-8">
							<div class="vertical">
								<div class="col-xs-12 nopadding">
									<div class="col-xs-12 noHorizontalPadding vpadding text-center">
										<img src="assets/img/icons/pruebas/img1.svg" alt="" class="col-xs-12 centered styled_1">
									</div>
									<h3 class="col-xs-12 noHorizontalPadding vpadding text-center nomargin">Manejo de múltiples almacenes o sucursales</h3>
									<div class="col-xs-12 nopadding text-center">
										<h4 class="col-xs-8 noHorizontalPadding centered nomargin">Asigna a tus colaboradores acceso a una o todas tus sucursales.</h4>
									</div>
								</div>
							</div>
						</div>
						<div class="col-xs-12 col-sm-4" style="background-image: url('assets/img/icons/pruebas/back_blue.jpg');">
							<div class="vertical">
								<div class="col-xs-12">
									<h4 class="col-xs-12 noHorizontalPadding vpadding nopaddingTop text-center textWhite">INICIAR SESIÓN</h4>
									<form class="col-xs-12 vpadding text-left" id="prueba_rapida">
  										<div class="form-group">
  										  	<label for="exampleInputEmail1">Email</label>
  										  	<input type="text" id="email" placeholder="Email">
  										</div>
  										<div class="form-group">
  										  	<label for="exampleInputEmail1">Contraseña</label>
  										  	<input type="password" id="contraseña" placeholder="Contraseña">
  										</div>
  										<div class="form-group">
											<div class="col-xs-12 noHorizontalPadding vpadding text-center">
												<a href="#" class="btn2 centered">ENVIAR</a>
											</div>
  										</div>
									</form>
								</div>
							</div>
						</div>
					</div>

					<div class="col-xs-12 item">
						<div class="col-xs-12 col-sm-8">
							<div class="vertical">
								<div class="col-xs-12 nopadding">
									<div class="col-xs-12 noHorizontalPadding vpadding text-center">
										<img src="assets/img/icons/pruebas/img1.svg" alt="" class="col-xs-12 centered styled_1">
									</div>
									<h3 class="col-xs-12 noHorizontalPadding vpadding text-center nomargin">Manejo de múltiples almacenes o sucursales</h3>
									<div class="col-xs-12 nopadding text-center">
										<h4 class="col-xs-8 noHorizontalPadding centered nomargin">Asigna a tus colaboradores acceso a una o todas tus sucursales.</h4>
									</div>
								</div>
							</div>
						</div>
						<div class="col-xs-12 col-sm-4" style="background-image: url('assets/img/icons/pruebas/back_blue.jpg');">
							<div class="vertical">
								<div class="col-xs-12">
									<h4 class="col-xs-12 noHorizontalPadding vpadding nopaddingTop text-center textWhite">INICIAR SESIÓN</h4>
									<form class="col-xs-12 vpadding text-left" id="prueba_rapida">
  										<div class="form-group">
  										  	<label for="exampleInputEmail1">Email</label>
  										  	<input type="text" id="email" placeholder="Email">
  										</div>
  										<div class="form-group">
  										  	<label for="exampleInputEmail1">Contraseña</label>
  										  	<input type="password" id="contraseña" placeholder="Contraseña">
  										</div>
  										<div class="form-group">
											<div class="col-xs-12 noHorizontalPadding vpadding text-center">
												<a href="#" class="btn2 centered">ENVIAR</a>
											</div>
  										</div>
									</form>
								</div>
							</div>
						</div>
					</div>
					
				</div>
			</div>
		</div>
	</div>
</section>