<section id="prueba2" class="backBlue startSection">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 nopadding">
				<h2 class="col-xs-12 noHorizontalPadding vxpadding nopaddingTop nomargin bold textBlue">Comienza tu prueba hoy</h2>
				<div class="col-xs-12 col-md-6 noHorizontalPadding vpadding text-center">
          <form class="col-xs-12 blue_circ centered" id="contact_prueba">
						<input type="hidden" name="captcha" id="captcha" value="">
						<div class="form-group">
              <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Nombre">
            </div>
						<div class="form-group">
              <input type="text" class="form-control" id="apellido" name="apellido" placeholder="Apellido">
            </div>
						<div class="form-group">
              <input type="text" class="form-control" id="correo" name="correo" placeholder="Correo Electrónico">
            </div>
						<div class="form-group">
              <input type="text" class="form-control" id="telefono" name="telefono" placeholder="Teléfono">
            </div>
						<div class="form-group">
              <input type="text" class="form-control" id="empresa" name="empresa" placeholder="Nombre de tu empresa">
            </div>
						<div class="form-group text-center nopadding nomargin">
              <button type="button" id="send_contact_prueba" class="centered">HAGAMOS NEGOCIOS</button>
            </div>
          </form>
				</div>
				<div class="col-xs-12 col-md-6 noHorizontalPadding vpadding text-center">
          <div class="col-xs-12 nopadding centered" id="carousel_slide">
						<div class="col-xs-12 item text-center">
							<div class="col-xs-12 noHorizontalPadding centered">
								<div class="col-xs-12 noHorizontalPadding vpadding text-center img">
	          			<img src="assets/img/testimonios/testimon_1.jpg" alt="" class="col-xs-12 noHorizontalPadding centered">
	          		</div>
								<div class="col-xs-12 noHorizontalPadding info text-left">
									<h4 class="bold">Luisa Sifuentes<small>MHUSA - Accesorios y bisutería</small></h4>
									<p class="text-center">Con SIGA puedo ver el stock de cualquiera de mis sucursales, y lo mejor de todo es que si en la tienda 1 tengo 50 unidades y en la tienda 2 tengo 200 unidades, puedo vender las 250 unidades, priorizando los negocios y ganando ventas.</p>
								</div>
							</div>
          	</div>
						<div class="col-xs-12 item text-center">
							<div class="col-xs-12 noHorizontalPadding centered">
								<div class="col-xs-12 noHorizontalPadding vpadding text-center">
	          			<img src="assets/img/testimonios/testimon_2.jpg" alt="" class="col-xs-12 noHorizontalPadding centered">
	          		</div>
								<div class="col-xs-12 noHorizontalPadding info text-left">
									<h4 class="bold">David Hernández<small>LEVELSTORE - Tienda On Line</small></h4>
									<p class="text-center">SIGA me permite promover ventas en mayor volumen, si el cliente venía a comprarme 10 unidades, puedo ofrecerle el 5% de descuento si compra 20, es muy práctico porque se aplica por producto.</p>
								</div>
							</div>
          	</div>
						<div class="col-xs-12 item text-center">
							<div class="col-xs-12 noHorizontalPadding centered">
								<div class="col-xs-12 noHorizontalPadding vpadding text-center">
	          			<img src="assets/img/testimonios/testimon_3.jpg" alt="" class="col-xs-12 noHorizontalPadding centered">
	          		</div>
								<div class="col-xs-12 noHorizontalPadding info text-left">
									<h4 class="bold">María Huanca<small>JCV THE BEST - Ferretería</small></h4>
									<p class="text-center">Con SIGA puedo llevar la cuenta de mis proveedores, o mis clientes a través del sistema puedo generar un cronograma de pagos, diario, interdiario, semanal, mensual o personalizado, y así saber qué días debo pagar.</p>
								</div>
							</div>
          	</div>
          </div>
				</div>
			</div>
		</div>
	</div>
</section>
