<section id="que_hara_siga_porti" class="startSection">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 nopadding">
				<h2 class="col-xs-12 noHorizontalPadding vxpadding nopaddingTop nomargin">¿Qué hará SIGA por ti?</h2>
			</div>
      <div class="col-xs-12 noHorizontalPadding vpadding items_beneficios">
        <div class="col-xs-12 col-md-6 nopadding text-center item">
          <div class="col-xs-12 nopadding centered">
            <div class="col-xs-12 nopadding info">
              <h3>FINANZAS</h3>
              <div>
                <p>Registra y controla tus compras, ventas y proveedores.</p>
                <p>Mantén al día tus cuentas por pagar, cobranzas, descuentos, flujo de caja.</p>
              </div>
            </div>
            <div class="col-xs-12 nopadding grey backGrey">
            </div>
            <img src="https://picsum.photos/400/400/?random" alt="">
          </div>
        </div>
        <div class="col-xs-12 col-md-6 nopadding text-center item">
          <div class="col-xs-12 nopadding centered">
            <div class="col-xs-12 nopadding info">
              <h3>VENTAS</h3>
              <div>
                <p>Podrás realizar ventas desde cualquier lugar del mundo en una computadora de escritorio, celular o tableta,  descargando  el APP SIGA desde play store</p>
              </div>
            </div>
            <div class="col-xs-12 nopadding grey backGrey">
            </div>
            <img src="https://picsum.photos/400/400/?random" alt="">
          </div>
        </div>
        <div class="col-xs-12 col-md-6 nopadding text-center item">
          <div class="col-xs-12 nopadding centered">
            <div class="col-xs-12 nopadding info">
              <h3>REPORTES</h3>
              <div>
                <p>Conoce el estado de tu negocio en tiempo real. Toma las mejores decisiones desde cualquier lugar.</p>
              </div>
            </div>
            <div class="col-xs-12 nopadding grey backGrey">
            </div>
            <img src="https://picsum.photos/400/400/?random" alt="">
          </div>
        </div>
        <div class="col-xs-12 col-md-6 nopadding text-center item">
          <div class="col-xs-12 nopadding centered">
            <div class="col-xs-12 nopadding info">
              <h3>CONTROL DE INVENTARIOS</h3>
              <div>
                <p>Controla tu inventario desde donde estés en tiempo real. Visualiza el estado actual de cada tienda o almacén.</p>
              </div>
            </div>
            <div class="col-xs-12 nopadding grey backGrey">
            </div>
            <img src="https://picsum.photos/400/400/?random" alt="">
          </div>
        </div>
      </div>
		</div>
	</div>
</section>
