<section id="que_hara_siga_porti3" class="startSection">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 nopadding">
				<h2 class="col-xs-12 noHorizontalPadding bold vxpadding nopaddingTop nomargin textBlue">¿Qué hará SIGA por ti?</h2>
			</div>
      <div class="col-xs-12 noHorizontalPadding vpadding que_hara_siga">

        <div class="col-xs-12 nopadding text-center item">
          <div class="col-xs-12 nopadding centered">
            <div class="col-xs-12 shadow">
              <div class="vertical">
                <div class="col-xs-12">
                  <h3 class="col-xs-12 noHorizontalPadding textBlue">Hará las cosas más sencillas para ti</h3>
                  <p class="col-xs-12 noHorizontalPadding">SIGA está creado para dinamizar y facilitar el proceso de venta. Y lograr que cualquier persona, sin ser experto en computación, pueda manejar el sistema de la mejor manera.</p>
                  <p class="col-xs-12 noHorizontalPadding">Más que un sistema será el socio Ideal para tu crecimiento empresarial.</p>
                </div>
              </div>
            </div>
            <img src="assets/img/que_hara_siga_porti/1.png" alt="">
          </div>
					<div class="col-xs-12 col-md-6 col-lg-5 testimonio text-left">
						<p class="col-xs-12 noHorizontalPadding">Desde que tengo SIGA, tomar pedidos y hacer facturas es un tema fácil. Mis clientes llegan a  mi negocio y llevan sus pedidos al momento.</p>
						<p class="col-xs-12 noHorizontalPadding">Además, mi información está ordenada y siempre  puedo revisarla en mi tablet.</p>
						<p class="col-xs-12 noHorizontalPadding name"><strong class="textBlue">José Quispe</strong> - Alimentos Brau S.A.C</p>
					</div>
        </div>

        <div class="col-xs-12 nopadding text-center item right">
          <div class="col-xs-12 nopadding centered">
            <div class="col-xs-12 shadow">
              <div class="vertical">
                <div class="col-xs-12">
                  <h3 class="col-xs-12 noHorizontalPadding textBlue">Hará las cosas más sencillas para ti</h3>
                  <p class="col-xs-12 noHorizontalPadding">SIGA está creado para dinamizar y facilitar el proceso de venta. Y lograr que cualquier persona, sin ser experto en computación, pueda manejar el sistema de la mejor manera.</p>
                  <p class="col-xs-12 noHorizontalPadding">Más que un sistema será el socio Ideal para tu crecimiento empresarial.</p>
                </div>
              </div>
            </div>
            <img src="assets/img/que_hara_siga_porti/2.png" alt="">
          </div>
					<div class="col-xs-12 col-md-6 col-lg-5 testimonio text-left">
						<p class="col-xs-12 noHorizontalPadding">Mis gastos en talonarios de facturas y papel térmico se han reducido casi al 90%, y ahora me toma menos de 5 minutos hacer una factura. SIGA ha sido una gran ayuda en este proceso de transición a facturación electrónica y lo ha hecho sencillo y rápido.</p>
						<p class="col-xs-12 noHorizontalPadding name"><strong class="textBlue">Angelo Peñafiel</strong> - Diseños D’Angello S.A.C</p>
					</div>
        </div>

				<div class="col-xs-12 nopadding text-center item">
          <div class="col-xs-12 nopadding centered">
            <div class="col-xs-12 shadow">
              <div class="vertical">
                <div class="col-xs-12">
                  <h3 class="col-xs-12 noHorizontalPadding textBlue">Hará que siempre te sientas respaldado</h3>
                  <p class="col-xs-12 noHorizontalPadding">En SIGA le damos el lugar que le corresponde al cliente o a la empresa, brindando el mejor soporte. Siempre estaremos atentos a tus dudas para resolverlas, puedes llamarnos, hablarnos por chat, WhatsApp , o enviarnos un email.</p>
                  <p class="col-xs-12 noHorizontalPadding">Siempre estaremos atentos a tus dudas para resolverlas, puedes llamarnos, hablarnos por chat, WhatsApp , o enviarnos un email.</p>
									<p class="col-xs-12 noHorizontalPadding">Además, tendrás videos tutoriales disponibles por cada módulo en nuestra pagina web para que puedas guiarte.</p>
								</div>
              </div>
            </div>
            <img src="assets/img/que_hara_siga_porti/3.png" alt="">
          </div>
					<div class="col-xs-12 col-md-6 col-lg-5 testimonio text-left">
						<p class="col-xs-12 noHorizontalPadding">Cada vez que tengo dudas, le escribo a mi asesor de ventas SIGA y él me resuelve al instante. El servicio que me han brindado es excelente.</p>
						<p class="col-xs-12 noHorizontalPadding name"><strong class="textBlue">Victor De Sousa</strong> - Comercial Portugal S.A.C</p>
					</div>
        </div>

				<div class="col-xs-12 nopadding text-center item right">
          <div class="col-xs-12 nopadding centered">
            <div class="col-xs-12 shadow">
              <div class="vertical">
                <div class="col-xs-12">
                  <h3 class="col-xs-12 noHorizontalPadding textBlue">Hará que puedas crecer sin limites</h3>
                  <p class="col-xs-12 noHorizontalPadding">SIGA se adaptará a ti  en tu crecimiento.</p>
                  <p class="col-xs-12 noHorizontalPadding">Siempre podrás incrementar Sucursales, Almacenes y tenerlos interconectados a un solo sistema.</p>
									<p class="col-xs-12 noHorizontalPadding">Nuestra misión será que puedas crecer y expandirte sin límites.</p>
								</div>
              </div>
            </div>
            <img src="assets/img/que_hara_siga_porti/4.png" alt="">
          </div>
					<div class="col-xs-12 col-md-6 col-lg-5 testimonio text-left">
						<p class="col-xs-12 noHorizontalPadding">Hace poco abrí una sucursal de mi negocio y no tuve problemas para adaptar SIGA. Ahora manejo mis tres tiendas desde un mismo sistema y todo desde la nube. Sé que cuando abra otra sucursal el proceso será igual de rápido y fácil.</p>
						<p class="col-xs-12 noHorizontalPadding name"><strong class="textBlue">Pedro Alvarado</strong> - Plásticos Alvarado S.A.C</p>
					</div>
        </div>

				<div class="col-xs-12 nopadding text-center item">
          <div class="col-xs-12 nopadding centered">
            <div class="col-xs-12 shadow">
              <div class="vertical">
                <div class="col-xs-12">
                  <h3 class="col-xs-12 noHorizontalPadding textBlue">Hará que puedas gerenciar tu empresa</h3>
                  <p class="col-xs-12 noHorizontalPadding">Dejarás de ser esclavo de tu negocio o tienda.</p>
                  <p class="col-xs-12 noHorizontalPadding">Podrás gerenciarlo  y así poder disfrutar de la vida al lado de tu familia, para que no se te vaya la vida trabajando.</p>
									<p class="col-xs-12 noHorizontalPadding">Tu negocio podrá desarrollarse sin la necesidad de tenerte a ti todo el día en tu tienda.</p>
								</div>
              </div>
            </div>
            <img src="assets/img/que_hara_siga_porti/5.png" alt="">
          </div>
					<div class="col-xs-12 col-md-6 col-lg-5 testimonio text-left">
						<p class="col-xs-12 noHorizontalPadding">Lo bueno de tener SIGA es que como toda la información está en linea, puedo buscar a mis hijos en el colegio sin tener miedo de perderme ni de mi empresa ni de mis hijos. Tengo más  tiempo libre para compartir con mi familia y ver todo lo que pasa en mi empresa desde el móvil.</p>
						<p class="col-xs-12 noHorizontalPadding name"><strong class="textBlue">María Leidenz</strong> - Bonita S.A.C</p>
					</div>
        </div>

      </div>
		</div>
	</div>
</section>
