<section id="icloudpos" class="startSection">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 nopadding">
				<h2 class="col-xs-12 noHorizontalPadding vxpadding nopaddingTop nomargin">¿Qué hará SIGA por ti?</h2>
			</div>
			<div class="col-xs-12 nopadding text_images">
				<div class="col-xs-12 col-sm-6 vpadding noHorizontalPadding">
					<div class="col-xs-12 col-sm-6">
						<img src="assets/img/icloudpos/1.svg" alt="" class="col-xs-12 nopadding">
					</div>
					<div class="col-xs-12 col-sm-6">
						<p class="col-xs-12 nopadding text-right"><strong>Ventas:</strong><br>Automatiza tus ventas, deja las libretas y cuadernos atrás. Realiza seguimiento constante a todo el ciclo comercial. Genera estadísticas de ventas en tiempo real.</p>
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 vpadding noHorizontalPadding">
					<div class="col-xs-12 col-sm-6">
						<p class="col-xs-12 nopadding text-left"><strong>Almacén: </strong><br>Mantén tu inventario actualizado en tiempo real. Maneja el stock de tus sucursales. Realiza ventas desde todos tus almacenes o sucursales.</p>
					</div>
					<div class="col-xs-12 col-sm-6">
						<img src="assets/img/icloudpos/2.svg" alt="" class="col-xs-12 nopadding">
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 vpadding noHorizontalPadding">
					<div class="col-xs-12 col-sm-6">
						<img src="assets/img/icloudpos/3.svg" alt="" class="col-xs-12 nopadding">
					</div>
					<div class="col-xs-12 col-sm-6">
						<p class="col-xs-12 nopadding text-right"><strong>Finanzas: </strong><br>Registra y controla tus compras y ventas, proveedores, cuentas por pagar, cobranzas, descuentos, flujo de caja. Facturas y boletas electrónicas integradas a SUNAT.</p>
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 vpadding noHorizontalPadding">
					<div class="col-xs-12 col-sm-6">
						<p class="col-xs-12 nopadding text-left"><strong>Reportes: </strong><br>Conoce el estado de tu negocio en tiempo real, toma las mejores decisiones desde cualquier lugar.</p>
					</div>
					<div class="col-xs-12 col-sm-6">
						<img src="assets/img/icloudpos/4.svg" alt="" class="col-xs-12 nopadding">
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
