<section id="partners" class="backWhite startSection">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 nopadding">
        <div class="col-xs-12 col-md-6 text-center">
          <h2 class="col-xs-12 noHorizontalPadding vxpadding nopaddingTop nomargin textBlue bold">Más que un sistema informático, una solución.</h2>
          <p>SIGA es un sistema informático que trabaja continuamente ofreciéndote soluciones de vanguardia.</p>
          <p>Buscamos la mejora en productos y servicios.</p>
          <p>Entendemos que la base de un negocio exitoso es una administración exitosa, y es lo que nos mantiene innovando y expandiendo nuestro sistema.</p>
        <div class="col-xs-12 noHorizontalPadding vpadding text-center">
          <a href="prueba" class="btn2 centered">QUIERO MI PRUEBA GRATIS</a>
        </div>
        </div>
        <div class="col-xs-12 col-md-6 icons">
          <div class="col-xs-6 nopadding text-center">
            <div class="col-xs-12 centered img">
              <img src="assets/img/icons/nosotros/rentable.svg" alt="">
            </div>
            <h5 class="textBlue">Rentable</h5>
          </div>
          <div class="col-xs-6 nopadding text-center">
            <div class="col-xs-12 centered img">
              <img src="assets/img/icons/nosotros/integral.svg" alt="">
            </div>
            <h5 class="textBlue">Integral</h5>
          </div>
          <div class="col-xs-6 nopadding text-center">
            <div class="col-xs-12 centered img">
              <img src="assets/img/icons/nosotros/simple.svg" alt="">
            </div>
            <h5 class="textBlue">Simple y fácil</h5>
          </div>
          <div class="col-xs-6 nopadding text-center">
            <div class="col-xs-12 centered img">
              <img src="assets/img/icons/nosotros/orden.svg" alt="">
            </div>
            <h5 class="textBlue">Ordenado</h5>
          </div>
        </div>
			</div>
		</div>
	</div>
</section>
