<section id="partners" class="backBlue startSection">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 nopadding">
				<h2 class="col-xs-12 noHorizontalPadding vxpadding nopaddingTop nomargin textBlue">Únete a SIGA y ofrece soluciones innovadoras y simples que cumplen con las necesidades de tus clientes</h2>
				<div class="col-xs-12 noHorizontalPadding vpadding modalidades">
					<div class="col-xs-12 col-sm-4 nopadding text-center item">
						<div class="col-xs-12 nopadding centered">
							<div class="col-xs-12 nopadding text-center">
								<img src="assets/img/icons/partner/emprendedor.svg" alt="" class="col-xs-12 nopadding centered">
							</div>
							<h3 class="col-xs-12 noHorizontalPadding text-center nomargin vpadding">EMPRENDEDOR</h3>
							<p class="col-xs-12 noHorizontalPadding vpadding nomargin nopaddingTop text-center">Compartes nuestra pasión por la innovación y ofrecer soluciones. SIGA es tu oportunidad de aprovechar un reto y convertirlo en oportunidad.</p>
							<div class="col-xs-12 noHorizontalPadding vpadding text-center">
								<a href="#" class="btn2 centered show_modal_contacto">YO SOY EMPRENDEDOR</a>
							</div>
						</div>
					</div>
					<div class="col-xs-12 col-sm-4 nopadding text-center item">
						<div class="col-xs-12 nopadding centered">
							<div class="col-xs-12 nopadding text-center">
								<img src="assets/img/icons/partner/empresa.svg" alt="" class="col-xs-12 nopadding centered">
							</div>
							<h3 class="col-xs-12 noHorizontalPadding text-center nomargin vpadding">EMPRESAS</h3>
							<p class="col-xs-12 noHorizontalPadding vpadding nomargin nopaddingTop text-center">Deseas expandir tu cartera de productos y servicios con el respaldo de un sistema informático de punta. SIGA es lo que estás buscando.</p>
							<div class="col-xs-12 noHorizontalPadding vpadding text-center">
								<a href="#" class="btn2 centered show_modal_contacto">YO SOY EMPRESA</a>
							</div>
						</div>
					</div>
					<div class="col-xs-12 col-sm-4 nopadding text-center item">
						<div class="col-xs-12 nopadding centered">
							<div class="col-xs-12 nopadding text-center">
								<img src="assets/img/icons/partner/consultor.svg" alt="" class="col-xs-12 nopadding centered">
							</div>
							<h3 class="col-xs-12 noHorizontalPadding text-center nomargin vpadding">CONSULTOR</h3>
							<p class="col-xs-12 noHorizontalPadding vpadding nomargin nopaddingTop text-center">Estás buscando la pieza que faltaba para ofrecer un servicio funcional de alta calidad a tus clientes. Haz la jugada con SIGA</p>
							<div class="col-xs-12 noHorizontalPadding vpadding text-center">
								<a href="#" class="btn2 centered show_modal_contacto">YO SOY CONSULTOR</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<section id="parters2">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 nopadding">
				<h2 class="col-xs-12 nopadding nomargin textWhite bold">Si ninguno se te acomoda, cuentanos<br>como trabajas</h2>
			</div>
		</div>
	</div>
</section>

<!-- Modal -->
<div class="modal fade modal_stetic" id="modal_contacto" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><img src="assets/img/closemodal.svg"></button>
			<div class="modal-body">
				<div class="row">
					<div class="col-xs-12 nopadding text-center">
						<form class="col-xs-12 blue_circ centered" id="Contacto">
							<input type="hidden" name="captcha" id="captcha" value="">
							<div class="form-group">
	              <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Nombre">
	            </div>
							<div class="form-group">
	              <input type="text" class="form-control" id="email" name="email" placeholder="Correo Electrónico">
	            </div>
							<div class="form-group">
	              <input type="text" class="form-control" id="telefono" name="telefono" placeholder="Teléfono">
	            </div>
							<div class="form-group">
								<textarea name="mensaje" id="mensaje" class="form-control" placeholder="Mensaje" rows="4" cols="80"></textarea>
	            </div>
							<div class="form-group text-center nopadding nomargin">
	              <button type="button" id="btnEnviar" class="centered">ENVIAR</button>
	            </div>
	          </form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
