<section id="facil_eficiente" class="startSection parallax_dev" data-parallax="scroll" data-position="mid mid" data-bleed="100" data-natural-width="1920" data-natural-height="1278" data-image-src="assets/img/facil_rapido_eficient.jpg">
	<div class="container">
		<div class="row">
      <div class="col-xs-12 noHorizontalPadding">
        <div class="col-xs-12 col-sm-6 pull-right text-right">
          <h1 class="col-xs-12 noHorizontalPadding nomarginTop textBlue">Fácil, rápido y eficiente</h1>
          <h4 class="col-xs-12 noHorizontalPadding nomarginTop bold">Con SIGA App podrás vender en cualquier lugar y en cualquiero momento</h4>
          <div class="col-xs-12 noHorizontalPadding vpadding eficiences">
						<div class="col-xs-6 col-sm-3 item text-center">
              <div class="col-xs-12 noHorizontalPadding centered">
                <img src="assets/img/icons/rapido_eficiente/ventas.svg" alt="" class="col-xs-12 noHorizontalPadding">
                <span class="col-xs-12 noHorizontalPadding">Ventas</span>
              </div>
            </div>
						<div class="col-xs-6 col-sm-3 item text-center">
              <div class="col-xs-12 noHorizontalPadding centered">
                <img src="assets/img/icons/rapido_eficiente/clientes.svg" alt="" class="col-xs-12 noHorizontalPadding">
                <span class="col-xs-12 noHorizontalPadding">Clientes</span>
              </div>
            </div>
						<div class="col-xs-6 col-sm-3 item text-center">
              <div class="col-xs-12 noHorizontalPadding centered">
                <img src="assets/img/icons/rapido_eficiente/inventario.svg" alt="" class="col-xs-12 noHorizontalPadding">
                <span class="col-xs-12 noHorizontalPadding">Inventario</span>
              </div>
            </div>
						<div class="col-xs-6 col-sm-3 item text-center">
              <div class="col-xs-12 noHorizontalPadding centered">
                <img src="assets/img/icons/rapido_eficiente/reportes.svg" alt="" class="col-xs-12 noHorizontalPadding">
                <span class="col-xs-12 noHorizontalPadding">Reportes de Ventas diarias</span>
              </div>
            </div>
          </div>
					<div class="col-xs-12 noHorizontalPadding">
						<a href="#" class="btn_gplay">
							<img src="assets/img/icons/rapido_eficiente/google-play.png" alt="" class="col-xs-12 noHorizontalPadding">
						</a>
					</div>
        </div>
      </div>
		</div>
	</div>
</section>

<section id="contactanos_ahora" class="nopaddingBottom">
	<div class="container">
		<div class="row">
      <div class="col-xs-12 noHorizontalPadding">
        <div class="col-xs-12 text-center">
          <h1 class="col-xs-12 noHorizontalPadding nomarginTop textOrange">Contáctanos ahora</h1>
          <h4 class="col-xs-12 noHorizontalPadding nomarginTop bold">Cómo quieres comunicarte con nosotros?</h4>
					<div class="col-xs-12 noHorizontalPadding vpadding text-center">
						<div class="col-xs-12 col-sm-12 col-md-10 col-lg-9 noHorizontalPadding centered">

							<div class="col-xs-6 col-sm-3 noHorizontalPadding text-center">
								<a href="#" class="centered btn_contacto_rap whats">
									<img src="assets/img/icons/contactanos_ahora/wp.svg" alt="">
									<span>WHATSAPP</span>
								</a>
							</div>

							<div class="col-xs-6 col-sm-3 noHorizontalPadding text-center">
								<a href="#" class="centered btn_contacto_rap email">
									<img src="assets/img/icons/contactanos_ahora/email.svg" alt="">
									<span>E-MAIL</span>
								</a>
							</div>

							<div class="col-xs-6 col-sm-3 noHorizontalPadding text-center">
								<a href="#" class="centered btn_contacto_rap llamada">
									<img src="assets/img/icons/contactanos_ahora/llamada.svg" alt="">
									<span>LLAMADA</span>
								</a>
							</div>

							<div class="col-xs-6 col-sm-3 noHorizontalPadding text-center">
								<a href="#" class="centered btn_contacto_rap hangouts">
									<img src="assets/img/icons/contactanos_ahora/hangouts.svg" alt="">
									<span>HANGOUTS</span>
								</a>
							</div>

						</div>
					</div>
					<h4 class="col-xs-12 noHorizontalPadding nomarginTop bold text-center">Prefieres una visita? Agéndala hoy</h4>
					<div class="col-xs-12 noHorizontalPadding text-center">
						<a href="#" class="btn5 centered">AGENDAR VISITA</a>
					</div>
        </div>
      </div>
		</div>
	</div>
</section>

<section id="planes" class="">
	<div class="container">
		<div class="row">
      <div class="col-xs-12 noHorizontalPadding">
        <div class="col-xs-12 text-center">
          <h1 class="col-xs-12 noHorizontalPadding nomarginTop textBlue">Planes</h1>
          <h4 class="col-xs-12 noHorizontalPadding nomarginTop bold">Nuestro servicio incluye soporte y asistencia permanente, no tenemos precios ocultos. Elige le plan que mejor se acomode a tu negocio.</h4>
					<div class="col-xs-12 noHorizontalPadding vpadding text-center planes_items">

						<div class="col-xs-12 col-sm-4 noHorizontalPadding text-center item">
							<div class="col-xs-12 centered">
								<div class="col-xs-12 noHorizontalPadding title">
									<div class="vertical">
										<div class="col-xs-12 noHorizontalPadding">
											<h1 class="col-xs-12 noHorizontalPadding nomargin textWhite">SIGA EXPERT</h1>
											<span class="col-xs-12 noHorizontalPadding textWhite">RECOMENDADO</span>
										</div>
									</div>
								</div>
								<div class="col-xs-12 info">
										<ul>
											<li>Facturación y boleta eletrónica</li>
											<li>Aplicativo de ventas</li>
											<li>Capacitaciones</li>
											<li>Soporte remoto / presencial</li>
											<li>6 Almacenes</li>
											<li>Kardex</li>
											<li>Convertir cotización a ventas</li>
											<li>Control de movimientos bancarios</li>
											<li>2 Sucursales</li>
											<li>E-commerce</li>
										</ul>
								</div>
								<div class="col-xs-12 noHorizontalPadding vpadding text-center btns">
									<div class="col-xs-12 noHorizontalPadding centered">
										<a href="#" class="blue">
											<img src="assets/img/icons/rapido_eficiente/search.svg" alt="">
											<span>VER MÀS</span>
										</a>
										<a href="#" class="green">
											<img src="assets/img/icons/rapido_eficiente/cart.svg" alt="">
											<span>CONTRATAR</span>
										</a>
									</div>
								</div>
							</div>
						</div>

						<div class="col-xs-12 col-sm-4 noHorizontalPadding text-center item light">
							<div class="col-xs-12 centered">
								<div class="col-xs-12 noHorizontalPadding title">
									<div class="vertical">
										<div class="col-xs-12 noHorizontalPadding">
											<h1 class="col-xs-12 noHorizontalPadding nomargin textWhite">SIGA ESTÁNDAR</h1>
										</div>
									</div>
								</div>
								<div class="col-xs-12 info">
										<ul>
											<li>Facturación y boleta eletrónica</li>
											<li>Aplicativo de ventas</li>
											<li>Capacitaciones</li>
											<li>Soporte remoto / presencial</li>
											<li>6 Almacenes</li>
											<li>Kardex</li>
											<li>Convertir cotización a ventas</li>
											<li>Control de movimientos bancarios</li>
											<li>2 Sucursales</li>
											<li class="red">E-commerce</li>
										</ul>
								</div>
								<div class="col-xs-12 noHorizontalPadding vpadding text-center btns">
									<div class="col-xs-12 noHorizontalPadding centered">
										<a href="#" class="blue">
											<img src="assets/img/icons/rapido_eficiente/search.svg" alt="">
											<span>VER MÀS</span>
										</a>
										<a href="#" class="green">
											<img src="assets/img/icons/rapido_eficiente/cart.svg" alt="">
											<span>CONTRATAR</span>
										</a>
									</div>
								</div>
							</div>
						</div>

						<div class="col-xs-12 col-sm-4 noHorizontalPadding text-center item light">
							<div class="col-xs-12 centered">
								<div class="col-xs-12 noHorizontalPadding title">
									<div class="vertical">
										<div class="col-xs-12 noHorizontalPadding">
											<h1 class="col-xs-12 noHorizontalPadding nomargin textWhite">SIGA BASIC</h1>
										</div>
									</div>
								</div>
								<div class="col-xs-12 info">
										<ul>
											<li>Facturación y boleta eletrónica</li>
											<li>Aplicativo de ventas</li>
											<li>Capacitaciones</li>
											<li>Soporte remoto / presencial</li>
											<li>6 Almacenes</li>
											<li class="red">Kardex</li>
											<li class="red">Convertir cotización a ventas</li>
											<li class="red">Control de movimientos bancarios</li>
											<li class="red">2 Sucursales</li>
											<li class="red">E-commerce</li>
										</ul>
								</div>
								<div class="col-xs-12 noHorizontalPadding vpadding text-center btns">
									<div class="col-xs-12 noHorizontalPadding centered">
										<a href="#" class="blue">
											<img src="assets/img/icons/rapido_eficiente/search.svg" alt="">
											<span>VER MÀS</span>
										</a>
										<a href="#" class="green">
											<img src="assets/img/icons/rapido_eficiente/cart.svg" alt="">
											<span>CONTRATAR</span>
										</a>
									</div>
								</div>
							</div>
						</div>

					</div>
        </div>
      </div>
		</div>
	</div>
</section>
