<section id="videos" class="startSection nopaddingBottom">
	<div class="container">
		<div class="row">
      <div class="col-xs-12 noHorizontalPadding">
        <div class="col-xs-12">
          <h1 class="col-xs-12 noHorizontalPadding nomarginTop textBlue text-center">Videos Tutoriales</h1>
          <div class="col-xs-12 noHorizontalPadding vpadding videos">

            <div class="col-xs-12 col-sm-6 col-md-3 noHorizontalPadding text-center item">
              <div class="col-xs-12 centered">
                <div class="col-xs-12 noHorizontalPadding media">
                  <iframe width="100%" height="auto" src="https://www.youtube.com/embed/9Kfu6ebes9Q?modestbranding=0&autohide=1&showinfo=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                </div>
                <h5 class="col-xs-12 noHorizontalPadding textBlue bold">Video Tutorial - <small>Cómo agregar existencia a un producto.</small></h5>
                <div class="col-xs-12 noHorizontalPadding text-center">
                  <a href="https://www.youtube.com/watch?v=9Kfu6ebes9Q" target="_blank" class="btn2 centered">VER VIDEO</a>
                </div>
              </div>
            </div>

            <div class="col-xs-12 col-sm-6 col-md-3 noHorizontalPadding text-center item">
              <div class="col-xs-12 centered">
                <div class="col-xs-12 noHorizontalPadding media">
                  <iframe width="100%" height="auto" src="https://www.youtube.com/embed/fDELsD5Fkmc?modestbranding=0&autohide=1&showinfo=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                </div>
                <h5 class="col-xs-12 noHorizontalPadding textBlue bold">Video Tutorial - <small>Realizar una venta.</small></h5>
                <div class="col-xs-12 noHorizontalPadding text-center">
                  <a href="https://www.youtube.com/watch?v=fDELsD5Fkmc" target="_blank" class="btn2 centered">VER VIDEO</a>
                </div>
              </div>
            </div>

            <div class="col-xs-12 col-sm-6 col-md-3 noHorizontalPadding text-center item">
              <div class="col-xs-12 centered">
                <div class="col-xs-12 noHorizontalPadding media">
                  <iframe width="100%" height="auto" src="https://www.youtube.com/embed/7PiuBM_LxMM?modestbranding=0&autohide=1&showinfo=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                </div>
                <h5 class="col-xs-12 noHorizontalPadding textBlue bold">Video Tutorial - <small>Realizar una cotización.</small></h5>
                <div class="col-xs-12 noHorizontalPadding text-center">
                  <a href="https://www.youtube.com/watch?v=7PiuBM_LxMM" target="_blank" class="btn2 centered">VER VIDEO</a>
                </div>
              </div>
            </div>

            <div class="col-xs-12 col-sm-6 col-md-3 noHorizontalPadding text-center item">
              <div class="col-xs-12 centered">
                <div class="col-xs-12 noHorizontalPadding media">
                  <iframe width="100%" height="auto" src="https://www.youtube.com/embed/1haHIiyqjpg?modestbranding=0&autohide=1&showinfo=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                </div>
                <h5 class="col-xs-12 noHorizontalPadding textBlue bold">Video Tutorial - <small>Ventas a credito.</small></h5>
                <div class="col-xs-12 noHorizontalPadding text-center">
                  <a href="https://www.youtube.com/watch?v=1haHIiyqjpg" target="_blank" class="btn2 centered">VER VIDEO</a>
                </div>
              </div>
            </div>




            <div class="col-xs-12 col-sm-6 col-md-3 noHorizontalPadding text-center item">
              <div class="col-xs-12 centered">
                <div class="col-xs-12 noHorizontalPadding media">
                  <iframe width="100%" height="auto" src="https://www.youtube.com/embed/PnMBOF9NCgY?modestbranding=0&autohide=1&showinfo=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                </div>
                <h5 class="col-xs-12 noHorizontalPadding textBlue bold">Video Tutorial - <small>Registrar un cliente.</small></h5>
                <div class="col-xs-12 noHorizontalPadding text-center">
                  <a href="https://www.youtube.com/watch?v=PnMBOF9NCgY" target="_blank" class="btn2 centered">VER VIDEO</a>
                </div>
              </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3 noHorizontalPadding text-center item">
              <div class="col-xs-12 centered">
                <div class="col-xs-12 noHorizontalPadding media">
                  <iframe width="100%" height="auto" src="https://www.youtube.com/embed/6qERQnTjZrc?modestbranding=0&autohide=1&showinfo=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                </div>
                <h5 class="col-xs-12 noHorizontalPadding textBlue bold">Video Tutorial - <small>Registrar usuarios y otorgar niveles.</small></h5>
                <div class="col-xs-12 noHorizontalPadding text-center">
                  <a href="https://www.youtube.com/watch?v=6qERQnTjZrc" target="_blank" class="btn2 centered">VER VIDEO</a>
                </div>
              </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3 noHorizontalPadding text-center item">
              <div class="col-xs-12 centered">
                <div class="col-xs-12 noHorizontalPadding media">
                  <iframe width="100%" height="auto" src="https://www.youtube.com/embed/I0pkmEZo0ss?modestbranding=0&autohide=1&showinfo=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                </div>
                <h5 class="col-xs-12 noHorizontalPadding textBlue bold">Video Tutorial - <small>Anular y devolver una venta.</small></h5>
                <div class="col-xs-12 noHorizontalPadding text-center">
                  <a href="https://www.youtube.com/watch?v=I0pkmEZo0ss" target="_blank" class="btn2 centered">VER VIDEO</a>
                </div>
              </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3 noHorizontalPadding text-center item">
              <div class="col-xs-12 centered">
                <div class="col-xs-12 noHorizontalPadding media">
                  <iframe width="100%" height="auto" src="https://www.youtube.com/embed/MqSL4IS6YVs?modestbranding=0&autohide=1&showinfo=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                </div>
                <h5 class="col-xs-12 noHorizontalPadding textBlue bold">Video Tutorial - <small>Agregar locales o tiendas.</small></h5>
                <div class="col-xs-12 noHorizontalPadding text-center">
                  <a href="https://www.youtube.com/watch?v=MqSL4IS6YVs" target="_blank" class="btn2 centered">VER VIDEO</a>
                </div>
              </div>
            </div>


            <div class="col-xs-12 col-sm-6 col-md-3 noHorizontalPadding text-center item">
              <div class="col-xs-12 centered">
                <div class="col-xs-12 noHorizontalPadding media">
                  <iframe width="100%" height="auto" src="https://www.youtube.com/embed/P4s2cm4_v8w?modestbranding=0&autohide=1&showinfo=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                </div>
                <h5 class="col-xs-12 noHorizontalPadding textBlue bold">Video Tutorial - <small>Registrar un producto.</small></h5>
                <div class="col-xs-12 noHorizontalPadding text-center">
                  <a href="https://www.youtube.com/watch?v=P4s2cm4_v8w" target="_blank" class="btn2 centered">VER VIDEO</a>
                </div>
              </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3 noHorizontalPadding text-center item">
              <div class="col-xs-12 centered">
                <div class="col-xs-12 noHorizontalPadding media">
                  <iframe width="100%" height="auto" src="https://www.youtube.com/embed/uRF80dBjI3s?modestbranding=0&autohide=1&showinfo=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                </div>
                <h5 class="col-xs-12 noHorizontalPadding textBlue bold">Video Tutorial - <small>Agregar unidades de presentación.</small></h5>
                <div class="col-xs-12 noHorizontalPadding text-center">
                  <a href="https://www.youtube.com/watch?v=uRF80dBjI3s" target="_blank" class="btn2 centered">VER VIDEO</a>
                </div>
              </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3 noHorizontalPadding text-center item">
              <div class="col-xs-12 centered">
                <div class="col-xs-12 noHorizontalPadding media">
                  <iframe width="100%" height="auto" src="https://www.youtube.com/embed/HMhoMxzFNf4?modestbranding=0&autohide=1&showinfo=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                </div>
                <h5 class="col-xs-12 noHorizontalPadding textBlue bold">Video Tutorial - <small>Anular compra.</small></h5>
                <div class="col-xs-12 noHorizontalPadding text-center">
                  <a href="https://www.youtube.com/watch?v=HMhoMxzFNf4" target="_blank" class="btn2 centered">VER VIDEO</a>
                </div>
              </div>
            </div>


          </div>
        </div>
      </div>
		</div>
	</div>
</section>
